name: Docker Image CI

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: Applications/ConsoleReferenceServer

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag referenceserver:$(date +%s)
