/* ========================================================================
 * Copyright (c) 2005-2025 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

namespace Opc.Ua.SourceGeneration
{
    /// <summary>
    /// Template strings
    /// </summary>
    internal static class CodeTemplates
    {
        /// <summary>
        /// Header
        /// </summary>
        public static string CodeHeader =>
            """
            // <auto-generated />
            /* ========================================================================
             * Copyright (c) 2005-2025 The OPC Foundation, Inc. All rights reserved.
             *
             * OPC Foundation MIT License 1.00
             *
             * Permission is hereby granted, free of charge, to any person
             * obtaining a copy of this software and associated documentation
             * files (the "Software"), to deal in the Software without
             * restriction, including without limitation the rights to use,
             * copy, modify, merge, publish, distribute, sublicense, and/or sell
             * copies of the Software, and to permit persons to whom the
             * Software is furnished to do so, subject to the following
             * conditions:
             *
             * The above copyright notice and this permission notice shall be
             * included in all copies or substantial portions of the Software.
             * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
             * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
             * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
             * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
             * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
             * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
             * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
             * OTHER DEALINGS IN THE SOFTWARE.
             *
             * The complete license agreement can be found here:
             * http://opcfoundation.org/License/MIT/1.00/
             * ======================================================================*/

            #nullable enable annotations
            #nullable disable warnings

            #pragma warning disable CS8019 // Unnecessary using directive
            #pragma warning disable 1591
            """;

        /// <summary>
        /// Const file template
        /// </summary>
        public static readonly TemplateString StatusCode_Attributes_File = TemplateString.Parse(
            $$"""
            {{Tokens.CodeHeader}}

            {{Tokens.ListOfImports}}

            namespace {{Tokens.Prefix}}
            {
                /// <summary>
                /// A class that defines constants for all {{Tokens.ClassName}}
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                public static partial class {{Tokens.ClassName}}
                {
                    {{Tokens.ListOfIdentifiers}}

                    {{Tokens.IdentifierReflection}}
                }
            }
            """);

        /// <summary>
        /// Constant declaration
        /// </summary>
        public static readonly TemplateString StatusCode_Attributes_Constant = TemplateString.Parse(
            $$"""
            /// <summary>
            /// {{Tokens.Description}}
            /// </summary>
            public const {{Tokens.IdType}} {{Tokens.SymbolicId}} = {{Tokens.Identifier}};

            """);

        /// <summary>
        /// Interning static constructor
        /// </summary>
        public static readonly TemplateString StatusCode_TypeInterning = TemplateString.Parse(
            $$"""
            static {{Tokens.ClassName}}()
            {
                {{Tokens.IdType}}.Intern(new {{Tokens.IdType}}[]
                {
                    {{Tokens.ListOfIdentifiers}}
                });
            }
            """);

        /// <summary>
        /// StatusCode declaration
        /// </summary>
        public static readonly TemplateString StatusCodes_Declaration = TemplateString.Parse(
            $$"""
            /// <summary>
            /// {{Tokens.Description}}
            /// </summary>
            public static readonly global::Opc.Ua.StatusCode {{Tokens.SymbolicId}} =
                new global::Opc.Ua.StatusCode({{Tokens.Identifier}}, nameof({{Tokens.SymbolicId}}));
            """);
    }
}
