/* ========================================================================
 * Copyright (c) 2005-2025 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Opc.Ua.SourceGeneration
{
    /// <summary>
    /// Generates source code for [DataType]-annotated classes and enums.
    /// Consumes a <see cref="DataTypeSourceModel"/> and produces C# source text
    /// using the template system shared with the model-based generators.
    /// </summary>
    internal static class DataTypeSourceGenerator
    {
        /// <summary>
        /// Generate the source text for a [DataType]-annotated type.
        /// </summary>
        /// <returns>The generated C# source code as a string.</returns>
        public static string Generate(DataTypeSourceModel model)
        {
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by OPC UA Source Generator for [DataType]-annotated types.");
            sb.AppendLine();
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");

            if (model.IsEnum)
            {
                GenerateEnumActivator(sb, model);
            }
            else
            {
                GeneratePartialClassBody(sb, model);
                GenerateStructureActivator(sb, model);
            }

            GenerateExtensionMethod(sb, model);

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void GeneratePartialClassBody(StringBuilder sb, DataTypeSourceModel model)
        {
            string typeIdExpr = FormatExpandedNodeIdExpression(model.DataTypeId, model.ClassName, model.NamespaceUri);
            string binaryIdExpr = FormatOptionalExpandedNodeIdExpression(model.BinaryEncodingId, model.NamespaceUri);
            string xmlIdExpr = FormatOptionalExpandedNodeIdExpression(model.XmlEncodingId, model.NamespaceUri);
            string jsonIdExpr = FormatOptionalExpandedNodeIdExpression(model.JsonEncodingId, model.NamespaceUri);
            string nsUriExpr = $"\"{EscapeString(model.NamespaceUri)}\"";

            sb.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Opc.Ua.SourceGeneration\", \"1.0.0\")]");
            sb.AppendLine($"    partial class {model.ClassName} :");
            sb.AppendLine($"        global::Opc.Ua.IEncodeable,");
            sb.AppendLine($"        global::Opc.Ua.IJsonEncodeable");
            sb.AppendLine("    {");

            // TypeId, BinaryEncodingId, XmlEncodingId, JsonEncodingId
            sb.AppendLine($"        /// <inheritdoc/>");
            sb.AppendLine($"        public virtual global::Opc.Ua.ExpandedNodeId TypeId => {typeIdExpr};");
            sb.AppendLine();
            sb.AppendLine($"        /// <inheritdoc/>");
            sb.AppendLine($"        public virtual global::Opc.Ua.ExpandedNodeId BinaryEncodingId => {binaryIdExpr};");
            sb.AppendLine();
            sb.AppendLine($"        /// <inheritdoc/>");
            sb.AppendLine($"        public virtual global::Opc.Ua.ExpandedNodeId XmlEncodingId => {xmlIdExpr};");
            sb.AppendLine();
            sb.AppendLine($"        /// <inheritdoc/>");
            sb.AppendLine($"        public virtual global::Opc.Ua.ExpandedNodeId JsonEncodingId => {jsonIdExpr};");
            sb.AppendLine();

            // Encode
            sb.AppendLine($"        /// <inheritdoc/>");
            sb.AppendLine($"        public virtual void Encode(global::Opc.Ua.IEncoder encoder)");
            sb.AppendLine("        {");
            sb.AppendLine($"            encoder.PushNamespace({nsUriExpr});");
            foreach (DataTypeSourceField field in model.Fields)
            {
                sb.AppendLine($"            encoder.{field.EncoderMethod}(\"{EscapeString(field.FieldName)}\", {field.PropertyName});");
            }
            sb.AppendLine($"            encoder.PopNamespace();");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Decode
            sb.AppendLine($"        /// <inheritdoc/>");
            sb.AppendLine($"        public virtual void Decode(global::Opc.Ua.IDecoder decoder)");
            sb.AppendLine("        {");
            sb.AppendLine($"            decoder.PushNamespace({nsUriExpr});");
            foreach (DataTypeSourceField field in model.Fields)
            {
                string readExpr = FormatReadExpression(field);
                sb.AppendLine($"            {field.PropertyName} = {readExpr};");
            }
            sb.AppendLine($"            decoder.PopNamespace();");
            sb.AppendLine("        }");
            sb.AppendLine();

            // IsEqual
            if (model.IsRecord)
            {
                sb.AppendLine($"        /// <inheritdoc/>");
                sb.AppendLine($"        public virtual bool IsEqual(global::Opc.Ua.IEncodeable encodeable)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return Equals(encodeable as {model.ClassName});");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        /// <inheritdoc/>");
                sb.AppendLine($"        object global::Opc.Ua.IEncodeable.Clone()");
                sb.AppendLine("        {");
                sb.AppendLine("            return this with { };");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine($"        /// <inheritdoc/>");
                sb.AppendLine($"        public virtual bool IsEqual(global::Opc.Ua.IEncodeable encodeable)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (encodeable is null) return false;");
                sb.AppendLine($"            if (object.ReferenceEquals(this, encodeable)) return true;");
                sb.AppendLine($"            {model.ClassName} value = encodeable as {model.ClassName};");
                sb.AppendLine($"            if (value is null) return false;");
                foreach (DataTypeSourceField field in model.Fields)
                {
                    string cmp = FormatCompareExpression(field);
                    sb.AppendLine($"            if ({cmp}) return false;");
                }
                sb.AppendLine($"            return true;");
                sb.AppendLine("        }");
                sb.AppendLine();

                // Clone
                sb.AppendLine($"        /// <inheritdoc/>");
                sb.AppendLine($"        public virtual object Clone()");
                sb.AppendLine("        {");
                sb.AppendLine($"            return ({model.ClassName})this.MemberwiseClone();");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        /// <inheritdoc/>");
                sb.AppendLine($"        public new object MemberwiseClone()");
                sb.AppendLine("        {");
                sb.AppendLine($"            {model.ClassName} clone = ({model.ClassName})base.MemberwiseClone();");
                foreach (DataTypeSourceField field in model.Fields)
                {
                    string cloneExpr = FormatCloneExpression(field);
                    if (cloneExpr != null)
                    {
                        sb.AppendLine($"            {cloneExpr}");
                    }
                }
                sb.AppendLine($"            return clone;");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void GenerateStructureActivator(StringBuilder sb, DataTypeSourceModel model)
        {
            string typeIdExpr = FormatExpandedNodeIdExpression(model.DataTypeId, model.ClassName, model.NamespaceUri);
            string nsUriExpr = $"\"{EscapeString(model.NamespaceUri)}\"";

            sb.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Opc.Ua.SourceGeneration\", \"1.0.0\")]");
            sb.AppendLine($"    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]");
            sb.AppendLine($"    public sealed class {model.ClassName}Activator : global::Opc.Ua.EncodeableType<{model.ClassName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {model.ClassName}Activator Instance = new {model.ClassName}Activator();");
            sb.AppendLine();
            sb.AppendLine($"        /// <inheritdoc/>");
            sb.AppendLine($"        public override global::System.Xml.XmlQualifiedName XmlName {{ get; }}");
            sb.AppendLine($"            = new global::System.Xml.XmlQualifiedName(\"{EscapeString(model.ClassName)}\", {nsUriExpr});");
            sb.AppendLine();
            sb.AppendLine($"        /// <inheritdoc/>");
            sb.AppendLine($"        public override global::Opc.Ua.IEncodeable CreateInstance()");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {model.ClassName}();");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void GenerateEnumActivator(StringBuilder sb, DataTypeSourceModel model)
        {
            string nsUriExpr = $"\"{EscapeString(model.NamespaceUri)}\"";

            sb.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Opc.Ua.SourceGeneration\", \"1.0.0\")]");
            sb.AppendLine($"    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]");
            sb.AppendLine($"    public sealed class {model.ClassName}Activator : global::Opc.Ua.EnumeratedType<{model.ClassName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {model.ClassName}Activator Instance = new {model.ClassName}Activator();");
            sb.AppendLine();
            sb.AppendLine($"        /// <inheritdoc/>");
            sb.AppendLine($"        public override global::System.Xml.XmlQualifiedName XmlName {{ get; }}");
            sb.AppendLine($"            = new global::System.Xml.XmlQualifiedName(\"{EscapeString(model.ClassName)}\", {nsUriExpr});");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void GenerateExtensionMethod(StringBuilder sb, DataTypeSourceModel model)
        {
            string typeIdExpr = FormatExpandedNodeIdExpression(model.DataTypeId, model.ClassName, model.NamespaceUri);
            string binaryIdExpr = FormatOptionalExpandedNodeIdExpression(model.BinaryEncodingId, model.NamespaceUri);
            string xmlIdExpr = FormatOptionalExpandedNodeIdExpression(model.XmlEncodingId, model.NamespaceUri);
            string jsonIdExpr = FormatOptionalExpandedNodeIdExpression(model.JsonEncodingId, model.NamespaceUri);

            sb.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Opc.Ua.SourceGeneration\", \"1.0.0\")]");
            sb.AppendLine($"    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]");
            sb.AppendLine($"    public static partial class {model.NamespaceSymbol}Extensions");
            sb.AppendLine("    {");

            if (model.IsEnum)
            {
                sb.AppendLine($"        public static global::Opc.Ua.IEncodeableFactoryBuilder Add{model.ClassName}(");
                sb.AppendLine($"            this global::Opc.Ua.IEncodeableFactoryBuilder builder)");
                sb.AppendLine("        {");
                sb.AppendLine($"            builder = builder");
                sb.AppendLine($"                .AddEnumeratedType({typeIdExpr}, {model.ClassName}Activator.Instance);");
                sb.AppendLine($"            return builder;");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine($"        public static global::Opc.Ua.IEncodeableFactoryBuilder Add{model.ClassName}(");
                sb.AppendLine($"            this global::Opc.Ua.IEncodeableFactoryBuilder builder)");
                sb.AppendLine("        {");
                sb.AppendLine($"            builder = builder");
                sb.AppendLine($"                .AddEncodeableType({typeIdExpr}, {model.ClassName}Activator.Instance);");
                if (model.BinaryEncodingId != null)
                {
                    sb.AppendLine($"            builder = builder");
                    sb.AppendLine($"                .AddEncodeableType({binaryIdExpr}, {model.ClassName}Activator.Instance);");
                }
                if (model.XmlEncodingId != null)
                {
                    sb.AppendLine($"            builder = builder");
                    sb.AppendLine($"                .AddEncodeableType({xmlIdExpr}, {model.ClassName}Activator.Instance);");
                }
                if (model.JsonEncodingId != null)
                {
                    sb.AppendLine($"            builder = builder");
                    sb.AppendLine($"                .AddEncodeableType({jsonIdExpr}, {model.ClassName}Activator.Instance);");
                }
                sb.AppendLine($"            return builder;");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
        }

        /// <summary>
        /// Maps common C# type names to IEncoder/IDecoder method name pairs.
        /// </summary>
        internal static readonly Dictionary<string, (string encoder, string decoder)> TypeMethodMap =
            new(StringComparer.Ordinal)
            {
                ["Boolean"] = ("WriteBoolean", "ReadBoolean"),
                ["SByte"] = ("WriteSByte", "ReadSByte"),
                ["Byte"] = ("WriteByte", "ReadByte"),
                ["Int16"] = ("WriteInt16", "ReadInt16"),
                ["UInt16"] = ("WriteUInt16", "ReadUInt16"),
                ["Int32"] = ("WriteInt32", "ReadInt32"),
                ["UInt32"] = ("WriteUInt32", "ReadUInt32"),
                ["Int64"] = ("WriteInt64", "ReadInt64"),
                ["UInt64"] = ("WriteUInt64", "ReadUInt64"),
                ["Float"] = ("WriteFloat", "ReadFloat"),
                ["Single"] = ("WriteFloat", "ReadFloat"),
                ["Double"] = ("WriteDouble", "ReadDouble"),
                ["String"] = ("WriteString", "ReadString"),
                ["DateTime"] = ("WriteDateTime", "ReadDateTime"),
                ["Guid"] = ("WriteGuid", "ReadGuid"),
                ["ByteString"] = ("WriteByteString", "ReadByteString"),
                ["Byte[]"] = ("WriteByteString", "ReadByteString"),
                ["NodeId"] = ("WriteNodeId", "ReadNodeId"),
                ["ExpandedNodeId"] = ("WriteExpandedNodeId", "ReadExpandedNodeId"),
                ["StatusCode"] = ("WriteStatusCode", "ReadStatusCode"),
                ["QualifiedName"] = ("WriteQualifiedName", "ReadQualifiedName"),
                ["LocalizedText"] = ("WriteLocalizedText", "ReadLocalizedText"),
                ["ExtensionObject"] = ("WriteExtensionObject", "ReadExtensionObject"),
                ["DataValue"] = ("WriteDataValue", "ReadDataValue"),
                ["Variant"] = ("WriteVariant", "ReadVariant"),
                ["DiagnosticInfo"] = ("WriteDiagnosticInfo", "ReadDiagnosticInfo"),
                ["Uuid"] = ("WriteGuid", "ReadGuid"),
                ["XmlElement"] = ("WriteXmlElement", "ReadXmlElement"),
            };

        /// <summary>
        /// Get the encoder/decoder method names for a field, or null if unknown.
        /// </summary>
        public static (string encoder, string decoder)? GetEncoderDecoderMethods(string shortTypeName)
        {
            if (TypeMethodMap.TryGetValue(shortTypeName, out var methods))
            {
                return methods;
            }
            return null;
        }

        private static string FormatExpandedNodeIdExpression(string idString, string className, string nsUri)
        {
            if (string.IsNullOrEmpty(idString))
            {
                return $"new global::Opc.Ua.ExpandedNodeId(\"{EscapeString(className)}\", \"{EscapeString(nsUri)}\")";
            }
            return $"global::Opc.Ua.ExpandedNodeId.Parse(\"{EscapeString(idString)}\", \"{EscapeString(nsUri)}\")";
        }

        private static string FormatOptionalExpandedNodeIdExpression(string idString, string nsUri)
        {
            if (string.IsNullOrEmpty(idString))
            {
                return "global::Opc.Ua.ExpandedNodeId.Null";
            }
            return $"global::Opc.Ua.ExpandedNodeId.Parse(\"{EscapeString(idString)}\", \"{EscapeString(nsUri)}\")";
        }

        private static string FormatReadExpression(DataTypeSourceField field)
        {
            if (field.IsEncodeable)
            {
                return $"({field.TypeName})decoder.ReadEncodeable(\"{EscapeString(field.FieldName)}\", typeof({field.TypeName}))";
            }
            if (field.IsEnum)
            {
                return $"({field.TypeName})decoder.ReadEnumerated(\"{EscapeString(field.FieldName)}\", typeof({field.TypeName}))";
            }
            return $"decoder.{field.DecoderMethod}(\"{EscapeString(field.FieldName)}\")";
        }

        private static string FormatCompareExpression(DataTypeSourceField field)
        {
            if (field.IsCollection)
            {
                return $"!global::Opc.Ua.Utils.IsEqual(this.{field.PropertyName}, value.{field.PropertyName})";
            }
            return $"!global::Opc.Ua.Utils.IsEqual(this.{field.PropertyName}, value.{field.PropertyName})";
        }

        private static string FormatCloneExpression(DataTypeSourceField field)
        {
            if (field.IsCollection)
            {
                return $"clone.{field.PropertyName} = ({field.TypeName})global::Opc.Ua.Utils.Clone(this.{field.PropertyName});";
            }
            if (field.IsEncodeable)
            {
                return $"clone.{field.PropertyName} = ({field.TypeName})global::Opc.Ua.Utils.Clone(this.{field.PropertyName});";
            }
            // Scalar value types and strings are handled by MemberwiseClone
            return null;
        }

        private static string EscapeString(string value)
        {
            if (value == null)
            {
                return string.Empty;
            }
#if NETSTANDARD2_0
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
#else
            return value.Replace("\\", "\\\\", StringComparison.Ordinal)
                .Replace("\"", "\\\"", StringComparison.Ordinal);
#endif
        }
    }
}
