/* ========================================================================
 * Copyright (c) 2005-2026 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Collections.Generic;
using System.IO;
using Opc.Ua.Schema.Model;
using Opc.Ua.Schema.Types;
using Opc.Ua.SourceGeneration.Snapshot;

namespace Opc.Ua.SourceGeneration
{
    /// <summary>
    /// Emits one <c>[assembly: Opc.Ua.ModelSnapshotAttribute(uri, payload)]</c>
    /// per emitted model so downstream source generators can resolve
    /// cross-assembly type references without the consumer adding the
    /// upstream NodeSet2/ModelDesign XML to <c>AdditionalFiles</c>. The
    /// payload is a Deflate-compressed, base64-encoded
    /// <see cref="ModelSnapshotV1"/>.
    /// </summary>
    internal sealed class ModelSnapshotGenerator : IGenerator
    {
        public ModelSnapshotGenerator(IGeneratorContext context)
        {
            m_context = context ?? throw new ArgumentNullException(nameof(context));
        }

        /// <inheritdoc/>
        public IEnumerable<Resource> Emit()
        {
            Namespace target = m_context.ModelDesign.TargetNamespace;
            if (target == null ||
                string.IsNullOrEmpty(target.Value) ||
                string.IsNullOrEmpty(target.Prefix))
            {
                return [];
            }
            // OpcUa root is implicit to every consumer; do not snapshot it.
            if (target.Value == Opc.Ua.Types.Namespaces.OpcUa)
            {
                return [];
            }

            ModelSnapshotV1 snapshot = BuildSnapshot(target);
            if (snapshot.Nodes.Count == 0)
            {
                return [];
            }

            string fileName = Path.Combine(
                m_context.OutputFolder,
                CoreUtils.Format("{0}.ModelSnapshot.g.cs", target.Prefix));

            using TextWriter writer = m_context.FileSystem.CreateTextWriter(fileName);
            string payload = snapshot.ToBase64Payload();
            writer.WriteLine("// <auto-generated />");
            writer.WriteLine("// Snapshot of model " + target.Value);
            writer.WriteLine("// Carries enough type-table data for downstream source");
            writer.WriteLine("// generators to resolve cross-namespace type references");
            writer.WriteLine("// without adding the upstream NodeSet2/ModelDesign XML.");
            writer.WriteLine();
            writer.WriteLine("#pragma warning disable CS8019 // Unnecessary using directive");
            writer.WriteLine("#pragma warning disable 1591");
            writer.WriteLine();
            writer.Write("[assembly: global::Opc.Ua.ModelSnapshotAttribute(");
            writer.WriteLine();
            writer.Write("    \"");
            writer.Write(EscapeForString(target.Value));
            writer.WriteLine("\",");
            writer.Write("    \"");
            writer.Write(payload);
            writer.WriteLine("\")]");
            return [fileName.AsTextFileResource()];
        }

        private ModelSnapshotV1 BuildSnapshot(Namespace target)
        {
            var snapshot = new ModelSnapshotV1 { ModelUri = target.Value };
            string targetUri = target.Value;
            foreach (NodeDesign node in m_context.ModelDesign.Nodes ?? [])
            {
                // Skip excluded / internal nodes.
                if (m_context.ModelDesign.IsExcluded(node))
                {
                    continue;
                }
                // Only snapshot types defined in this target namespace.
                // Types from referenced namespaces (e.g. OpcUa root) are
                // resolved by the consumer from its own references.
                if (node.SymbolicId is null ||
                    !string.Equals(node.SymbolicId.Namespace, targetUri, StringComparison.Ordinal))
                {
                    continue;
                }
                if (node is not TypeDesign type)
                {
                    continue;
                }
                SnapshotNodeKind kind = type switch
                {
                    ObjectTypeDesign => SnapshotNodeKind.ObjectType,
                    VariableTypeDesign => SnapshotNodeKind.VariableType,
                    ReferenceTypeDesign => SnapshotNodeKind.ReferenceType,
                    DataTypeDesign => SnapshotNodeKind.DataType,
                    _ => SnapshotNodeKind.Unknown
                };
                if (kind == SnapshotNodeKind.Unknown)
                {
                    continue;
                }
                var entry = new SnapshotNode
                {
                    SymbolicName = type.SymbolicId.Name ?? string.Empty,
                    SymbolicNamespace = type.SymbolicId.Namespace ?? string.Empty,
                    ClassName = type.ClassName ?? type.SymbolicId.Name ?? string.Empty,
                    Kind = kind,
                    BaseTypeName = type.BaseType?.Name,
                    BaseTypeNamespace = type.BaseType?.Namespace,
                    NumericId = type.NumericIdSpecified ? type.NumericId : 0u,
                    StringId = string.IsNullOrEmpty(type.StringId) ? null : type.StringId,
                    IsAbstract = type.IsAbstract
                };
                if (type is DataTypeDesign dataType)
                {
                    entry.IsEnumeration = dataType.IsEnumeration;
                    if (dataType.Fields != null && dataType.Fields.Length > 0)
                    {
                        var fields = new List<SnapshotDataField>(dataType.Fields.Length);
                        foreach (Parameter field in dataType.Fields)
                        {
                            if (field == null) { continue; }
                            fields.Add(new SnapshotDataField(
                                name: field.Name ?? string.Empty,
                                dataTypeName: field.DataType?.Name ?? string.Empty,
                                dataTypeNamespace: field.DataType?.Namespace ?? string.Empty,
                                valueRank: (int)field.ValueRank));
                        }
                        entry.Fields = fields;
                    }
                }
                else
                {
                    // For ObjectType / VariableType / ReferenceType, carry
                    // their declared InstanceDesign children so downstream
                    // consumers can recognise inherited members and suppress
                    // duplicate emission.
                    if (type.HasChildren && type.Children?.Items != null)
                    {
                        var children = new List<SnapshotChild>(type.Children.Items.Length);
                        foreach (InstanceDesign child in type.Children.Items)
                        {
                            if (child == null) { continue; }
                            byte instanceKind = child switch
                            {
                                PropertyDesign => (byte)3,
                                VariableDesign => (byte)2,
                                MethodDesign => (byte)4,
                                _ => (byte)1
                            };
                            byte modellingRule = child.ModellingRule switch
                            {
                                ModellingRule.Mandatory => (byte)1,
                                ModellingRule.Optional => (byte)2,
                                ModellingRule.OptionalPlaceholder => (byte)3,
                                ModellingRule.MandatoryPlaceholder => (byte)4,
                                ModellingRule.ExposesItsArray => (byte)5,
                                _ => (byte)0
                            };
                            children.Add(new SnapshotChild(
                                browseName: child.BrowseName ?? child.SymbolicName?.Name ?? string.Empty,
                                symbolicName: child.SymbolicName?.Name ?? string.Empty,
                                modellingRule: modellingRule,
                                instanceKind: instanceKind));
                        }
                        if (children.Count > 0)
                        {
                            entry.Children = children;
                        }
                    }
                }
                snapshot.Nodes.Add(entry);
            }
            // Deterministic order so the assembly is byte-reproducible.
            snapshot.Nodes.Sort((a, b) =>
            {
                int c = string.CompareOrdinal(a.SymbolicNamespace, b.SymbolicNamespace);
                return c != 0 ? c : string.CompareOrdinal(a.SymbolicName, b.SymbolicName);
            });
            return snapshot;
        }

        private static string EscapeForString(string value)
        {
            return value
                .Replace("\\", "\\\\", StringComparison.Ordinal)
                .Replace("\"", "\\\"", StringComparison.Ordinal);
        }

        private readonly IGeneratorContext m_context;
    }
}
