/* ========================================================================
 * Copyright (c) 2005-2025 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Collections.Generic;
using System.IO;

namespace Opc.Ua.SourceGeneration
{
    /// <summary>
    /// Generates the WellKnownServerCapabilities catalog from
    /// the embedded ServerCapabilities.csv design file.
    /// </summary>
    internal class ServerCapabilitiesGenerator : IGenerator
    {
        /// <summary>
        /// Create the server capabilities generator.
        /// </summary>
        public ServerCapabilitiesGenerator(IGeneratorContext context)
        {
            m_context = context ?? throw new ArgumentNullException(nameof(context));
        }

        /// <inheritdoc/>
        public IEnumerable<Resource> Emit()
        {
            string fileName = Path.Combine(
                m_context.OutputFolder,
                CoreUtils.Format(
                    "{0}.WellKnownServerCapabilities.g.cs",
                    Constants.CoreNamespacePrefix));

            List<Capability> capabilities = LoadCapabilities(
                BuiltInDesignFiles.ServerCapabilitiesCsv);

            using TextWriter writer = m_context.FileSystem.CreateTextWriter(fileName);
            WriteFile(writer, capabilities);

            return [fileName.AsTextFileResource()];
        }

        /// <summary>
        /// Loads the (id, description) capability entries from a CSV file.
        /// </summary>
        private List<Capability> LoadCapabilities(string capabilitiesFile)
        {
            var capabilities = new List<Capability>();

            using TextReader reader = m_context.FileSystem.CreateTextReader(capabilitiesFile);
            while (true)
            {
                string line = reader.ReadLine();
                if (line == null)
                {
                    break;
                }

                // strip a UTF-8 BOM if present on the first row.
                if (line.Length > 0 && line[0] == '\uFEFF')
                {
                    line = line.Substring(1);
                }

                if (string.IsNullOrWhiteSpace(line))
                {
                    continue;
                }

                int index = line.IndexOf(',');
                if (index < 0)
                {
                    continue;
                }

                string id = line.Substring(0, index).Trim();
                string description = line.Substring(index + 1).Trim();
                if (id.Length == 0)
                {
                    continue;
                }

                capabilities.Add(new Capability(id, description));
            }

            return capabilities;
        }

        /// <summary>
        /// Writes the generated WellKnownServerCapabilities source file.
        /// </summary>
        private static void WriteFile(TextWriter writer, List<Capability> capabilities)
        {
            writer.WriteLine("// <auto-generated>");
            writer.WriteLine("//     This code was generated by the OPC UA source generator.");
            writer.WriteLine("//     Do not modify; changes will be overwritten on the next build.");
            writer.WriteLine("// </auto-generated>");
            writer.WriteLine();
            writer.WriteLine("#nullable disable");
            writer.WriteLine();
            writer.WriteLine("using System.Collections.Generic;");
            writer.WriteLine();
            writer.WriteLine("namespace Opc.Ua.Gds");
            writer.WriteLine("{");
            writer.WriteLine("    /// <summary>");
            writer.WriteLine(
                "    /// Well known OPC UA server capability identifiers as defined in");
            writer.WriteLine(
                "    /// <see href=\"https://reference.opcfoundation.org/\" />.");
            writer.WriteLine("    /// </summary>");
            writer.WriteLine(
                "    /// <remarks>");
            writer.WriteLine(
                "    /// Generated from the ServerCapabilities.csv design file.");
            writer.WriteLine(
                "    /// </remarks>");
            writer.WriteLine("    public static class WellKnownServerCapabilities");
            writer.WriteLine("    {");

            for (int i = 0; i < capabilities.Count; i++)
            {
                Capability c = capabilities[i];
                if (i > 0)
                {
                    writer.WriteLine();
                }
                writer.WriteLine("        /// <summary>{0}</summary>", ToSummary(c.Description));
                writer.WriteLine(
                    "        public const string {0} = \"{1}\";",
                    ToSymbol(c.Id),
                    EscapeString(c.Id));
            }

            writer.WriteLine();
            writer.WriteLine("        /// <summary>");
            writer.WriteLine(
                "        /// All known capability identifiers keyed by their identifier.");
            writer.WriteLine("        /// </summary>");
            writer.WriteLine(
                "        public static readonly IReadOnlyDictionary<string, string> All =");
            writer.WriteLine("            new Dictionary<string, string>");
            writer.WriteLine("            {");
            for (int i = 0; i < capabilities.Count; i++)
            {
                Capability c = capabilities[i];
                writer.WriteLine(
                    "                {{ \"{0}\", \"{1}\" }},",
                    EscapeString(c.Id),
                    EscapeString(c.Description));
            }
            writer.WriteLine("            };");

            writer.WriteLine("    }");
            writer.WriteLine("}");
        }

        /// <summary>
        /// Maps a CSV id to a valid C# identifier. Ids that begin with a
        /// digit (e.g., "61850") are prefixed with "Iec".
        /// </summary>
        private static string ToSymbol(string id)
        {
            if (id.Length == 0)
            {
                return id;
            }
            if (char.IsDigit(id[0]))
            {
                return "Iec" + id;
            }
            return id;
        }

        /// <summary>
        /// Produces a short single-line XML summary text from a description.
        /// </summary>
        private static string ToSummary(string description)
        {
            if (string.IsNullOrEmpty(description))
            {
                return string.Empty;
            }

            string text = description.Trim();

            // first sentence wins, otherwise the first 80 chars.
            int dot = text.IndexOf('.');
            if (dot > 0)
            {
                text = text.Substring(0, dot + 1);
            }
            else if (text.Length > 80)
            {
                text = text.Substring(0, 80);
            }

            return EscapeXml(text);
        }

        private static string EscapeString(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return value ?? string.Empty;
            }
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string EscapeXml(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return value ?? string.Empty;
            }
            return value
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }

        private sealed class Capability
        {
            public Capability(string id, string description)
            {
                Id = id;
                Description = description;
            }

            public string Id { get; }
            public string Description { get; }
        }

        private readonly IGeneratorContext m_context;
    }
}
