/* ========================================================================
 * Copyright (c) 2005-2025 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

namespace Opc.Ua.SourceGeneration
{
    /// <summary>
    /// Templates for source-annotated [DataType] types.
    /// These emit into the user's existing partial class/enum.
    /// Activator and registration templates are reused from <see cref="DataTypeTemplates"/>.
    /// </summary>
    internal static class TypeSourceTemplates
    {
        /// <summary>
        /// Top-level file template for a source-annotated data type.
        /// </summary>
        public static readonly TemplateString File = TemplateString.Parse(
            $$"""
            // <auto-generated/>
            // Generated by OPC UA Source Generator for [DataType]-annotated types.
            #pragma warning disable CS1591

            namespace {{Tokens.NamespacePrefix}}
            {
                {{Tokens.ListOfTypes}}

                {{Tokens.ListOfTypeActivators}}

                /// <summary>
                /// Extension methods to add [DataType]-annotated types to an encodeable factory.
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
                {{Tokens.AccessModifier}} static partial class {{Tokens.Namespace}}DataTypeExtensions
                {
                    /// <summary>
                    /// Adds all [DataType]-annotated encodeables of the {{Tokens.NamespaceUri}} namespace.
                    /// </summary>
                    {{Tokens.AccessModifier}} static global::Opc.Ua.IEncodeableFactoryBuilder Add{{Tokens.Namespace}}DataTypes(
                        this global::Opc.Ua.IEncodeableFactoryBuilder builder)
                    {
                        {{Tokens.ListOfActivatorRegistrations}}

                        return builder;
                    }
                }
            }
            """);

        /// <summary>
        /// Partial class body implementing IEncodeable for a source-annotated class.
        /// The user defines the class, properties, and constructor; we add the
        /// IEncodeable interface members.
        /// </summary>
        public static readonly TemplateString PartialClassBody = TemplateString.Parse(
            $$"""
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            {{Tokens.AccessModifier}} partial class {{Tokens.ClassName}} :
                global::Opc.Ua.IEncodeable,
                global::Opc.Ua.IJsonEncodeable
            {
                {{Tokens.ListOfInitOnlyBackingFields}}
                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId TypeId
                    => {{Tokens.DataTypeIdConstant}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId BinaryEncodingId
                    => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId XmlEncodingId
                    => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId JsonEncodingId
                    => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public virtual void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfEncodedFields}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfDecodedFields}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    if (encodeable is null)
                    {
                        return false;
                    }

                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.ClassName}} value = encodeable as {{Tokens.ClassName}};
                    if (value is null)
                    {
                        return false;
                    }

                    {{Tokens.ListOfComparedFields}}

                    return true;
                }

                {{Tokens.ListOfChildCopies}}
            }
            """);

        /// <summary>
        /// Partial class body for a sealed root class.
        /// Same as <see cref="PartialClassBody"/> but without <c>virtual</c> modifiers.
        /// </summary>
        public static readonly TemplateString SealedPartialClassBody = TemplateString.Parse(
            $$"""
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            {{Tokens.AccessModifier}} partial class {{Tokens.ClassName}} :
                global::Opc.Ua.IEncodeable,
                global::Opc.Ua.IJsonEncodeable
            {
                {{Tokens.ListOfInitOnlyBackingFields}}
                /// <inheritdoc/>
                public global::Opc.Ua.ExpandedNodeId TypeId
                    => {{Tokens.DataTypeIdConstant}};

                /// <inheritdoc/>
                public global::Opc.Ua.ExpandedNodeId BinaryEncodingId
                    => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public global::Opc.Ua.ExpandedNodeId XmlEncodingId
                    => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public global::Opc.Ua.ExpandedNodeId JsonEncodingId
                    => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfEncodedFields}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfDecodedFields}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    if (encodeable is null)
                    {
                        return false;
                    }

                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.ClassName}} value = encodeable as {{Tokens.ClassName}};
                    if (value is null)
                    {
                        return false;
                    }
            
                    {{Tokens.ListOfComparedFields}}

                    return true;
                }

                {{Tokens.ListOfChildCopies}}
            }
            """);

        /// <summary>
        /// Partial class body for a non-sealed derived class.
        /// Uses <c>override</c> instead of <c>virtual</c>, calls base in
        /// Encode, Decode and IsEqual, and omits the interface list.
        /// </summary>
        public static readonly TemplateString DerivedPartialClassBody = TemplateString.Parse(
            $$"""
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            {{Tokens.AccessModifier}} partial class {{Tokens.ClassName}}
            {
                {{Tokens.ListOfInitOnlyBackingFields}}
                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId TypeId
                    => {{Tokens.DataTypeIdConstant}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId BinaryEncodingId
                    => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId XmlEncodingId
                    => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId JsonEncodingId
                    => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public override void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    base.Encode(encoder);
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfEncodedFields}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    base.Decode(decoder);
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfDecodedFields}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    if (encodeable is null)
                    {
                        return false;
                    }

                    if (object.ReferenceEquals(this, encodeable))
                    {
                        return true;
                    }

                    {{Tokens.ClassName}} value = encodeable as {{Tokens.ClassName}};
                    if (value is null)
                    {
                        return false;
                    }

                    {{Tokens.ListOfComparedFields}}

                    return base.IsEqual(encodeable);
                }

                {{Tokens.ListOfChildCopies}}
            }
            """);

        /// <summary>
        /// Partial class body for a record type. Clone/IsEqual/GetHashCode
        /// delegate to the record implementation.
        /// </summary>
        public static readonly TemplateString RecordPartialClassBody = TemplateString.Parse(
            $$"""
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            partial record class {{Tokens.ClassName}} :
                global::Opc.Ua.IEncodeable,
                global::Opc.Ua.IJsonEncodeable
            {
                {{Tokens.ListOfInitOnlyBackingFields}}
                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId TypeId
                    => {{Tokens.DataTypeIdConstant}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId BinaryEncodingId
                    => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId XmlEncodingId
                    => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public virtual global::Opc.Ua.ExpandedNodeId JsonEncodingId
                    => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public virtual void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfEncodedFields}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfDecodedFields}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public virtual bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    return Equals(encodeable as {{Tokens.ClassName}});
                }
            
                {{Tokens.ListOfChildCopies}}
            }
            """);

        /// <summary>
        /// Partial class body for a sealed record type.
        /// Same as RecordPartialClassBody but no virtual keyword.
        /// </summary>
        public static readonly TemplateString SealedRecordPartialClassBody = TemplateString.Parse(
            $$"""
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            partial record class {{Tokens.ClassName}} :
                global::Opc.Ua.IEncodeable,
                global::Opc.Ua.IJsonEncodeable
            {
                {{Tokens.ListOfInitOnlyBackingFields}}
                /// <inheritdoc/>
                public global::Opc.Ua.ExpandedNodeId TypeId
                    => {{Tokens.DataTypeIdConstant}};

                /// <inheritdoc/>
                public global::Opc.Ua.ExpandedNodeId BinaryEncodingId
                    => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public global::Opc.Ua.ExpandedNodeId XmlEncodingId
                    => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public global::Opc.Ua.ExpandedNodeId JsonEncodingId
                    => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfEncodedFields}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfDecodedFields}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    return Equals(encodeable as {{Tokens.ClassName}});
                }

                {{Tokens.ListOfChildCopies}}
            }
            """);

        /// <summary>
        /// Partial class body for a derived record type.
        /// Uses override + base.Encode/Decode. Clone/IsEqual
        /// delegate to the record implementation.
        /// </summary>
        public static readonly TemplateString DerivedRecordPartialClassBody = TemplateString.Parse(
            $$"""
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{Tokens.Tool}}", "{{Tokens.Version}}")]
            partial record class {{Tokens.ClassName}}
            {
                {{Tokens.ListOfInitOnlyBackingFields}}
                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId TypeId
                    => {{Tokens.DataTypeIdConstant}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId BinaryEncodingId
                    => {{Tokens.BinaryEncodingId}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId XmlEncodingId
                    => {{Tokens.XmlEncodingId}};

                /// <inheritdoc/>
                public override global::Opc.Ua.ExpandedNodeId JsonEncodingId
                    => {{Tokens.JsonEncodingId}};

                /// <inheritdoc/>
                public override void Encode(global::Opc.Ua.IEncoder encoder)
                {
                    base.Encode(encoder);
                    encoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfEncodedFields}}
                    encoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override void Decode(global::Opc.Ua.IDecoder decoder)
                {
                    base.Decode(decoder);
                    decoder.PushNamespace({{Tokens.XmlNamespaceUri}});
                    {{Tokens.ListOfDecodedFields}}
                    decoder.PopNamespace();
                }

                /// <inheritdoc/>
                public override bool IsEqual(global::Opc.Ua.IEncodeable encodeable)
                {
                    return Equals(encodeable as {{Tokens.ClassName}});
                }
            }
            """);

        /// <summary>
        /// Clone method
        /// </summary>
        public static readonly TemplateString CloneMethod = TemplateString.Parse(
            $$"""
            /// <inheritdoc/>
            public {{Tokens.AccessModifier}} object Clone()
            {
                {{Tokens.ClassName}} clone = new {{Tokens.ClassName}}();
                {{Tokens.ListOfClonedFields}}
                return clone;
            }
            
            """);

        /// <summary>
        /// Clone method
        /// </summary>
        public static readonly TemplateString RecordCloneMethod = TemplateString.Parse(
            $$"""
            /// <inheritdoc/>
            object global::System.ICloneable.Clone()
            {
                {{Tokens.ClassName}} clone = this with { };
                {{Tokens.ListOfClonedFields}}
                return clone;
            }
                  
            """);

        /// <summary>
        /// Activator registration for a source-annotated structure type.
        /// Uses inline ExpandedNodeId literals instead of DataTypeIds constants.
        /// </summary>
        public static readonly TemplateString SourceActivatorRegistration = TemplateString.Parse(
            $$"""
            builder = builder
                .AddEncodeableType({{Tokens.DataTypeIdConstant}}, {{Tokens.ClassName}}Activator.Instance)
                .AddEncodeableType({{Tokens.BinaryEncodingId}}, {{Tokens.ClassName}}Activator.Instance)
                .AddEncodeableType({{Tokens.XmlEncodingId}}, {{Tokens.ClassName}}Activator.Instance)
                .AddEncodeableType({{Tokens.JsonEncodingId}}, {{Tokens.ClassName}}Activator.Instance);
            """);

        /// <summary>
        /// Activator registration for a source-annotated enum type.
        /// </summary>
        public static readonly TemplateString SourceEnumActivatorRegistration = TemplateString.Parse(
            $$"""
            builder = builder
                .AddEnumeratedType({{Tokens.DataTypeIdConstant}}, {{Tokens.ClassName}}Activator.Instance);
            """);
    }
}
