/* ========================================================================
 * Copyright (c) 2005-2026 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System.Threading;
using System.Threading.Tasks;
using Opc.Ua.Security.Certificates;

namespace Opc.Ua.Server
{
    /// <summary>
    /// Persists the private key regenerated by <c>CreateSigningRequest</c>
    /// (<c>regeneratePrivateKey=true</c>, OPC 10000-12 §7.10.10) so it
    /// survives across Sessions and process restart until a matching
    /// <c>UpdateCertificate</c> consumes it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Entries are scoped by certificate group and certificate type: at
    /// most one pending key exists per (group, type) pair. A later
    /// <see cref="SaveAsync"/> call for the same pair replaces (and the
    /// implementation disposes) any previous entry.
    /// </para>
    /// <para>
    /// Implementations that cannot guarantee the material is persisted
    /// somewhere more durable than process memory MUST return
    /// <see langword="false"/> from <see cref="SaveAsync"/> so the caller
    /// can reject the request with <see cref="StatusCodes.BadNotSupported"/>
    /// instead of silently keeping the key only in memory.
    /// </para>
    /// </remarks>
    public interface IPendingCertificateKeyStore
    {
        /// <summary>
        /// Persists <paramref name="certificateWithPrivateKey"/> for the
        /// scope described by <paramref name="context"/>, replacing (and
        /// disposing) any previously saved entry for the same scope.
        /// </summary>
        /// <remarks>
        /// The caller retains ownership of <paramref name="certificateWithPrivateKey"/>
        /// and may dispose it as soon as this call returns; implementations
        /// that need to retain the instance itself (rather than exporting
        /// its bytes) must call <c>AddRef()</c> on it.
        /// </remarks>
        /// <returns>
        /// <see langword="true"/> when the key was durably persisted;
        /// <see langword="false"/> when this store cannot durably persist
        /// the supplied scope (for example, an unsupported certificate
        /// store type) and the caller must not proceed as if it had been.
        /// </returns>
        ValueTask<bool> SaveAsync(
            PendingCertificateKeyContext context,
            Certificate certificateWithPrivateKey,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieves and removes (consumes) the pending key for the scope
        /// described by <paramref name="context"/>, or returns
        /// <see langword="null"/> when none is present. The caller owns
        /// and must dispose the returned <see cref="Certificate"/>.
        /// </summary>
        ValueTask<Certificate?> TryTakeAsync(
            PendingCertificateKeyContext context,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Removes (discards) the pending key for the scope described by
        /// <paramref name="context"/>, if any. Used when a superseded
        /// signing request, a <c>CreateSelfSignedCertificate</c>, a
        /// <c>DeleteCertificate</c>, or a successful activation makes the
        /// pending key obsolete.
        /// </summary>
        ValueTask RemoveAsync(
            PendingCertificateKeyContext context,
            CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// Identifies the scope of a pending regenerated private key and
    /// carries the collaborators an <see cref="IPendingCertificateKeyStore"/>
    /// needs to persist it securely.
    /// </summary>
    /// <param name="BaseStore">
    /// The certificate group's configured application-certificate store.
    /// Secure implementations derive their own storage location from this
    /// (for example, a dedicated sub-path) rather than mixing pending keys
    /// into the active certificate store.
    /// </param>
    /// <param name="CertificateGroupId">The owning certificate group NodeId.</param>
    /// <param name="CertificateTypeId">The certificate type NodeId.</param>
    /// <param name="PasswordProvider">
    /// Optional password provider used to protect the persisted key
    /// material, consistent with how the active certificate store protects
    /// private keys.
    /// </param>
    /// <param name="Telemetry">Telemetry context used to open stores and create loggers.</param>
    public sealed record PendingCertificateKeyContext(
        CertificateStoreIdentifier BaseStore,
        NodeId CertificateGroupId,
        NodeId CertificateTypeId,
        ICertificatePasswordProvider? PasswordProvider,
        ITelemetryContext Telemetry);
}
