/* ========================================================================
 * Copyright (c) 2005-2025 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;

namespace Opc.Ua.SourceGeneration
{
    /// <summary>
    /// A pooled structure deriving from a structure of another model's
    /// assembly must not depend on members only the current generator
    /// emits into that assembly.
    /// </summary>
    [TestFixture]
    [Category("SourceGeneration")]
    [SetCulture("en-us")]
    [SetUICulture("en-us")]
    public class CrossModelPooledStructureTests
    {
        /// <summary>
        /// E-1: the derived pooled extension overrides and calls
        /// base.ResetForReuse(), which a base structure generated by an
        /// older generator does not have (CS0115/CS0117). A base from
        /// another model now gets the variant that relies only on Reuse().
        /// </summary>
        [Test]
        public void DerivedStructureCompilesAgainstBaseWithoutResetForReuse()
        {
            CSharpCompilation producer = GenerateProducerWithoutResetForReuse();

            CSharpCompilation consumer = ModelDependencyScannerTests
                .CreateStackCompilation("PooledConsumer")
                .AddReferences(producer.ToMetadataReference());
            GeneratorDriver driver = CreateDriver("ModelB.xml", ModelBDesign);
            driver = driver.RunGeneratorsAndUpdateCompilation(
                consumer,
                out Compilation output,
                out ImmutableArray<Diagnostic> diagnostics);

            Assert.That(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error), Is.Empty);
            string generated = string.Join(
                "\n",
                driver.GetRunResult().Results[0].GeneratedSources.Select(s => s.SourceText.ToString()));
            Assert.That(generated, Does.Contain("partial class DerivedStruct"));
            Assert.That(generated, Does.Not.Contain("base.ResetForReuse()"));
            Assert.That(
                output.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error),
                Is.Empty,
                string.Join(Environment.NewLine, output.GetDiagnostics()));
        }

        /// <summary>
        /// Generates ModelA and strips the overridable ResetForReuse() from
        /// its pooled extension, which is what a ModelA assembly built by
        /// the previous generator looks like.
        /// </summary>
        private static CSharpCompilation GenerateProducerWithoutResetForReuse()
        {
            CSharpCompilation compilation = ModelDependencyScannerTests
                .CreateStackCompilation("PooledProducer");
            GeneratorDriver driver = CreateDriver("ModelA.xml", ModelADesign);
            driver = driver.RunGeneratorsAndUpdateCompilation(
                compilation,
                out Compilation _,
                out ImmutableArray<Diagnostic> diagnostics);
            Assert.That(diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error), Is.Empty);

            CSharpParseOptions parseOptions = new CSharpParseOptions()
                .WithKind(SourceCodeKind.Regular)
                .WithLanguageVersion(LanguageVersion.CSharp11);
            bool stripped = false;
            foreach (GeneratedSourceResult source in driver.GetRunResult().Results[0].GeneratedSources)
            {
                string text = source.SourceText.ToString();
                if (text.Contains("protected virtual void ResetForReuse()", StringComparison.Ordinal))
                {
                    text = text
                        .Replace(
                            "protected virtual void ResetForReuse()",
                            "private void OldGeneratorReset()",
                            StringComparison.Ordinal)
                        .Replace("ResetForReuse();", "OldGeneratorReset();", StringComparison.Ordinal);
                    stripped = true;
                }
                compilation = compilation.AddSyntaxTrees(
                    CSharpSyntaxTree.ParseText(text, parseOptions, source.HintName));
            }
            Assert.That(stripped, Is.True, "the producer has a pooled structure");
            Assert.That(
                compilation.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error),
                Is.Empty,
                string.Join(Environment.NewLine, compilation.GetDiagnostics()));
            return compilation;
        }

        private static GeneratorDriver CreateDriver(string path, string design)
        {
            var options = new AnalyzerOptionsProvider(
                new Dictionary<string, string>
                {
                    ["build_property.ModelSourceGeneratorOmitFluentApi"] = "true",
                    ["build_property.ModelSourceGeneratorOmitEventRecords"] = "true"
                });
            return CSharpGeneratorDriver.Create(new ModelSourceGenerator())
                .WithUpdatedParseOptions(new CSharpParseOptions()
                    .WithKind(SourceCodeKind.Regular)
                    .WithLanguageVersion(LanguageVersion.CSharp11))
                .AddAdditionalTexts([EmbeddedText.Create(path, design)])
                .WithUpdatedAnalyzerConfigOptions(options);
        }

        private const string ModelADesign =
            """
            <?xml version="1.0" encoding="utf-8" ?>
            <opc:ModelDesign
              xmlns:opc="http://opcfoundation.org/UA/ModelDesign.xsd"
              xmlns:ua="http://opcfoundation.org/UA/"
              xmlns="http://test.org/UA/PooledA/"
              TargetNamespace="http://test.org/UA/PooledA/">
              <opc:Namespaces>
                <opc:Namespace Name="OpcUa" Prefix="Opc.Ua" XmlNamespace="http://opcfoundation.org/UA/2008/02/Types.xsd">http://opcfoundation.org/UA/</opc:Namespace>
                <opc:Namespace Name="PooledA" Prefix="Test.PooledA">http://test.org/UA/PooledA/</opc:Namespace>
              </opc:Namespaces>
              <opc:DataType SymbolicName="BaseStruct" BaseType="ua:Structure">
                <opc:Fields>
                  <opc:Field Name="Make" DataType="ua:String" />
                  <opc:Field Name="Note" DataType="ua:String" IsOptional="true" />
                </opc:Fields>
              </opc:DataType>
            </opc:ModelDesign>
            """;

        private const string ModelBDesign =
            """
            <?xml version="1.0" encoding="utf-8" ?>
            <opc:ModelDesign
              xmlns:opc="http://opcfoundation.org/UA/ModelDesign.xsd"
              xmlns:ua="http://opcfoundation.org/UA/"
              xmlns:s0="http://test.org/UA/PooledA/"
              xmlns="http://test.org/UA/PooledB/"
              TargetNamespace="http://test.org/UA/PooledB/">
              <opc:Namespaces>
                <opc:Namespace Name="PooledB" Prefix="Test.PooledB">http://test.org/UA/PooledB/</opc:Namespace>
                <opc:Namespace Name="PooledA" Prefix="Test.PooledA">http://test.org/UA/PooledA/</opc:Namespace>
                <opc:Namespace Name="OpcUa" Prefix="Opc.Ua" XmlNamespace="http://opcfoundation.org/UA/2008/02/Types.xsd">http://opcfoundation.org/UA/</opc:Namespace>
              </opc:Namespaces>
              <opc:DataType SymbolicName="DerivedStruct" BaseType="s0:BaseStruct">
                <opc:Fields>
                  <opc:Field Name="Extra" DataType="ua:UInt32" />
                </opc:Fields>
              </opc:DataType>
            </opc:ModelDesign>
            """;
    }
}
