/* ========================================================================
 * Copyright (c) 2005-2026 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Globalization;
using System.Text;
using System.Text.Json;
using static System.FormattableString;
using NUnit.Framework;
using Opc.Ua.Export;
using Opc.Ua.Wot;

namespace Opc.Ua.WotCon.Tests.Samples
{
    /// <summary>
    /// Measures what the readable mapping alone produces for the sample pump.
    /// It is explicit because it writes a report rather than asserting: its
    /// purpose is to pin the true delta before the mapping is changed.
    /// </summary>
    /// <remarks>
    /// The difference count of <c>NodeSetComparer</c> is deliberately not used
    /// here. Canonical-XML comparison stops at the first mismatch, so it once
    /// reported a single difference between two wholly unrelated documents.
    /// This dumps both node lists in full instead.
    /// </remarks>
    [TestFixture]
    public sealed class ReadableMappingProbe
    {
        [Test]
        [Explicit]
        public void DumpReadableMappingDelta()
        {
            string documents = Path.Combine(
                TestContext.CurrentContext.TestDirectory,
                "..", "..", "..", "..", "..",
                "samples", "WotCon", "AggregationClient", "Documents");
            UANodeSet source = ReadNodeSet(Path.Combine(documents, "SamplePump.NodeSet2.xml"));

            var report = new StringBuilder();
            var options = new WotNodeSetConverterOptions
            {
                MaxJsonDocumentSize = 16 * 1024 * 1024
            };

            using WotDocument generated = WotNodeSetConverter.FromNodeSet(
                source, "Sample Pump Aggregate");
            byte[] raw = generated.ToCanonicalUtf8();
            report.AppendLine("generated bytes: " + raw.Length.ToString(CultureInfo.InvariantCulture));

            using (JsonDocument parsed = JsonDocument.Parse(raw))
            {
                JsonElement root = parsed.RootElement;
                report.AppendLine("uav:nodes present  : " +
                    root.TryGetProperty("uav:nodes", out _).ToString());
                report.AppendLine("uav:nodeSet present: " +
                    root.TryGetProperty("uav:nodeSet", out _).ToString());
                foreach (string kind in new[] { "properties", "actions", "events" })
                {
                    if (!root.TryGetProperty(kind, out JsonElement collection))
                    {
                        report.AppendLine(kind + ": absent");
                        continue;
                    }
                    int browseNames = 0;
                    int ids = 0;
                    int total = 0;
                    foreach (JsonProperty entry in collection.EnumerateObject())
                    {
                        total++;
                        if (entry.Value.TryGetProperty("uav:browseName", out _))
                        {
                            browseNames++;
                        }
                        if (entry.Value.TryGetProperty("uav:id", out _))
                        {
                            ids++;
                        }
                    }
                    report.AppendLine(Invariant($"{kind}: {total} (uav:browseName={browseNames}, uav:id={ids})"));
                }
            }

            using WotDocument readable = WotDocument.Parse(StripNative(raw), options);
            WotConversionResult<UANodeSet> result =
                WotNodeSetConverter.ToNodeSetResult(readable, options);
            report.AppendLine();
            report.AppendLine("reverse conversion success: " + result.Success.ToString());
            foreach (WotDiagnostic diagnostic in result.Diagnostics)
            {
                report.AppendLine(Invariant($"   {diagnostic.Severity} {diagnostic.Code}: {diagnostic.Message}"));
            }

            AppendDocumentSet(report, source, options);

            AppendNodes(report, "SOURCE", source);
            if (result.Value is not null)
            {
                AppendNodes(report, "ROUNDTRIP", result.Value);
            }

            string path = Path.Combine(
                TestContext.CurrentContext.TestDirectory, "readable-mapping-delta.txt");
            File.WriteAllText(path, report.ToString());
            TestContext.Out.WriteLine(path);
        }

        private static void AppendNodes(StringBuilder report, string label, UANodeSet nodeSet)
        {
            report.AppendLine();
            report.AppendLine(Invariant($"=== {label}: {nodeSet.Items?.Length ?? 0} node(s)"));
            report.AppendLine(
                "namespaces: " + string.Join(" | ", nodeSet.NamespaceUris ?? []));
            report.AppendLine(
                "models: " + string.Join(
                    " | ", (nodeSet.Models ?? []).Select(model => model.ModelUri)));
            foreach (UANode node in (nodeSet.Items ?? [])
                .OrderBy(item => item.NodeId, StringComparer.Ordinal))
            {
                report.AppendLine(Invariant($"   {node.GetType().Name,-12} {node.NodeId,-48} {node.BrowseName}"));
            }
        }

        private static void AppendDocumentSet(
            StringBuilder report, UANodeSet source, WotNodeSetConverterOptions options)
        {
            report.AppendLine();
            report.AppendLine("=== DOCUMENT SET");
            WotConversionResult<WotDocumentSet> set =
                WotNodeSetConverter.FromNodeSetDocuments(
                    source, "sample-pump", "Sample Pump Aggregate", options);
            foreach (WotDiagnostic diagnostic in set.Diagnostics)
            {
                report.AppendLine(Invariant($"   {diagnostic.Severity} {diagnostic.Code}: {diagnostic.Message}"));
            }
            if (set.Value is null)
            {
                report.AppendLine("   no set produced");
                return;
            }
            using WotDocumentSet documents = set.Value;
            report.AppendLine(Invariant($"   entries: {documents.Entries.Count} (root '{documents.RootHref}')"));
            for (int i = 0; i < documents.Entries.Count; i++)
            {
                WotDocumentSetEntry entry = documents.Entries[i];
                report.AppendLine(Invariant(
                    $"   {entry.Href,-46} properties={entry.Document.Properties.Count}") +
                    Invariant(
                        $" actions={entry.Document.Actions.Count}") +
                    Invariant(
                        $" events={entry.Document.Events.Count}"));
            }

            WotConversionResult<UANodeSet> merged = WotNodeSetConverter
                .ToNodeSetAsync(documents, options, CompanionContext(options))
                .AsTask().GetAwaiter().GetResult();
            foreach (WotDiagnostic diagnostic in merged.Diagnostics)
            {
                report.AppendLine(Invariant($"   merge {diagnostic.Severity} {diagnostic.Code}: {diagnostic.Message}"));
            }
            if (merged.Value is not null)
            {
                AppendNodes(report, "SET ROUNDTRIP", merged.Value);
                AppendMissing(report, source, merged.Value);
            }
        }

        /// <summary>
        /// Names the source Nodes the round-trip did not reproduce, and the ones
        /// it invented. This is what <c>NodeSetComparer</c> cannot show: its
        /// canonical-XML comparison stops at the first mismatch.
        /// </summary>
        private static void AppendMissing(
            StringBuilder report, UANodeSet source, UANodeSet roundtrip)
        {
            var produced = new HashSet<string>(
                (roundtrip.Items ?? []).Select(node => node.NodeId ?? string.Empty),
                StringComparer.Ordinal);
            var expected = new HashSet<string>(
                (source.Items ?? []).Select(node => node.NodeId ?? string.Empty),
                StringComparer.Ordinal);
            report.AppendLine();
            report.AppendLine("=== MISSING from the round trip");
            foreach (string nodeId in expected.Except(produced).OrderBy(id => id, StringComparer.Ordinal))
            {
                report.AppendLine("   " + nodeId);
            }
            report.AppendLine("=== EXTRA in the round trip");
            foreach (string nodeId in produced.Except(expected).OrderBy(id => id, StringComparer.Ordinal))
            {
                report.AppendLine("   " + nodeId);
            }

            report.AppendLine("=== ATTRIBUTE differences on shared Nodes");
            Dictionary<string, UANode> sourceIndex = (source.Items ?? [])
                .Where(node => node.NodeId is not null)
                .ToDictionary(node => node.NodeId!, StringComparer.Ordinal);
            foreach (UANode node in (roundtrip.Items ?? [])
                .OrderBy(item => item.NodeId, StringComparer.Ordinal))
            {
                if (node.NodeId is null ||
                    !sourceIndex.TryGetValue(node.NodeId, out UANode? original))
                {
                    continue;
                }
                foreach (string difference in DescribeDifferences(original, node))
                {
                    report.AppendLine(Invariant($"   {node.NodeId}: {difference}"));
                }
            }
        }

        private static IEnumerable<string> DescribeDifferences(UANode expected, UANode actual)
        {
            if (!string.Equals(expected.BrowseName, actual.BrowseName, StringComparison.Ordinal))
            {
                yield return $"BrowseName '{expected.BrowseName}' -> '{actual.BrowseName}'";
            }
            if (expected is UAVariable expectedVariable && actual is UAVariable actualVariable)
            {
                if (!string.Equals(
                        expectedVariable.DataType, actualVariable.DataType, StringComparison.Ordinal))
                {
                    yield return
                        $"DataType '{expectedVariable.DataType}' -> '{actualVariable.DataType}'";
                }
                if (expectedVariable.AccessLevel != actualVariable.AccessLevel)
                {
                    yield return
                        $"AccessLevel {expectedVariable.AccessLevel} -> {actualVariable.AccessLevel}";
                }
                if ((expectedVariable.Value is not null) != (actualVariable.Value is not null))
                {
                    yield return "Value " +
                        (expectedVariable.Value is not null ? "present -> absent" : "absent -> present");
                }
            }
            string expectedType = TypeDefinitionOf(expected);
            string actualType = TypeDefinitionOf(actual);
            if (!string.Equals(expectedType, actualType, StringComparison.Ordinal))
            {
                yield return $"HasTypeDefinition '{expectedType}' -> '{actualType}'";
            }
        }

        private static string TypeDefinitionOf(UANode node)
        {
            foreach (Reference reference in node.References ?? [])
            {
                if (string.Equals(
                        reference.ReferenceType, "HasTypeDefinition", StringComparison.Ordinal) &&
                    reference.IsForward)
                {
                    return reference.Value ?? string.Empty;
                }
            }
            return string.Empty;
        }

        /// <summary>
        /// The local context of §5.1.5 for this pump: the companion Thing Models
        /// that define the types its Nodes are instances of.
        /// </summary>
        private static WotDocumentNodeResolver CompanionContext(
            WotNodeSetConverterOptions options)
        {
            string documents = Path.Combine(
                TestContext.CurrentContext.TestDirectory,
                "..", "..", "..", "..", "..",
                "samples", "WotCon", "AggregationClient", "Documents");
            var loaded = new List<WotDocument>();
            foreach (string name in new[]
            {
                "Opc.Ua.Di.tm.json", "Opc.Ua.Machinery.tm.json", "Opc.Ua.Pumps.tm.json"
            })
            {
                loaded.Add(WotDocument.Parse(
                    File.ReadAllBytes(Path.Combine(documents, name)), options));
            }
            return new WotDocumentNodeResolver(loaded);
        }

        private static byte[] StripNative(byte[] json)
        {
            using JsonDocument parsed = JsonDocument.Parse(json);
            using var output = new MemoryStream();
            using (var writer = new Utf8JsonWriter(output))
            {
                writer.WriteStartObject();
                foreach (JsonProperty member in parsed.RootElement.EnumerateObject())
                {
                    if (member.Name is not ("uav:nodes" or "uav:nodeSet"))
                    {
                        writer.WritePropertyName(member.Name);
                        member.Value.WriteTo(writer);
                    }
                }
                writer.WriteEndObject();
            }
            return output.ToArray();
        }

        private static UANodeSet ReadNodeSet(string path)
        {
            using FileStream stream = File.OpenRead(path);
            return UANodeSet.Read(stream) ??
                throw new InvalidOperationException($"'{path}' is not a NodeSet2 document.");
        }
    }
}
