/* ========================================================================
 * Copyright (c) 2005-2026 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Buffers.Binary;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Opc.Ua.Security.Certificates;
using Opc.Ua.Server;

namespace Opc.Ua.Redundancy.Server
{
    /// <summary>
    /// Extension beyond OPC 10000-4 §6.6: a distributed
    /// <see cref="IPendingCertificateKeyStore"/> that persists the private key
    /// regenerated by <c>CreateSigningRequest</c> (OPC 10000-12 §7.10.10) into
    /// an <see cref="ISharedKeyValueStore"/> so it survives across replicas of
    /// a <c>RedundantServerSet</c> until a matching <c>UpdateCertificate</c>
    /// consumes it - even when that <c>UpdateCertificate</c> lands on a
    /// different replica than the one that ran <c>CreateSigningRequest</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Each pending key is exported as a password-protected PKCS#12 blob, then
    /// the whole record (the ephemeral password and the PKCS#12 bytes) is
    /// passed through an <see cref="IRecordProtector"/> so the private key is
    /// encrypted and integrity-protected at rest; a tampered or forged record
    /// fails verification and is treated as absent (fail-closed). Entries are
    /// scoped per certificate group and certificate type, matching the
    /// single-pending-key-per-slot contract, and the store key is derived from
    /// the scope so the raw NodeIds never appear verbatim in the keyspace.
    /// </para>
    /// <para>
    /// <see cref="TryTakeAsync"/> claims the entry with an atomic
    /// compare-and-swap so at most one replica consumes a given pending key,
    /// even if two replicas race. Every working buffer that holds private key
    /// material is wiped before the call returns; the caller owns and must
    /// dispose the returned <see cref="Certificate"/>.
    /// </para>
    /// </remarks>
    public sealed class SharedKeyValuePendingCertificateKeyStore : IPendingCertificateKeyStore
    {
        /// <summary>
        /// Creates a distributed pending-key store over a shared key/value
        /// backend.
        /// </summary>
        /// <param name="store">The shared key/value backend.</param>
        /// <param name="options">The distributed PushManagement options.</param>
        /// <param name="protector">
        /// Optional record protector applied to every stored pending key
        /// (authenticated encryption); defaults to a no-op pass-through.
        /// Configure an <see cref="AesCbcHmacRecordProtector"/> in production so
        /// the shared store can be treated as untrusted.
        /// </param>
        public SharedKeyValuePendingCertificateKeyStore(
            ISharedKeyValueStore store,
            DistributedPushConfigurationOptions options,
            IRecordProtector? protector = null)
        {
            m_store = store ?? throw new ArgumentNullException(nameof(store));
            if (options == null)
            {
                throw new ArgumentNullException(nameof(options));
            }
            m_prefix = options.PendingKeyPrefix;
            m_protector = protector ?? NullRecordProtector.Instance;
        }

        /// <inheritdoc/>
        public async ValueTask<bool> SaveAsync(
            PendingCertificateKeyContext context,
            Certificate certificateWithPrivateKey,
            CancellationToken cancellationToken = default)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }
            if (certificateWithPrivateKey == null)
            {
                throw new ArgumentNullException(nameof(certificateWithPrivateKey));
            }

            char[] passcode = GeneratePasscode();
            byte[]? passcodeBytes = null;
            byte[]? pkcs12 = null;
            byte[]? blob = null;
            try
            {
                pkcs12 = certificateWithPrivateKey.Export(X509ContentType.Pfx, passcode);
                passcodeBytes = Encoding.UTF8.GetBytes(passcode);
                blob = EncodeRecord(passcodeBytes, pkcs12);

                var plaintext = new ByteString(blob);
                ByteString payload = m_protector.Protect(plaintext);
                await m_store.SetAsync(KeyFor(context), payload, cancellationToken).ConfigureAwait(false);

                // The no-op protector stores the plaintext buffer verbatim, so
                // wiping it here would corrupt the stored record; a real
                // protector produces an independent ciphertext envelope, so the
                // plaintext buffer can (and must) be wiped.
                if (!payload.Equals(plaintext))
                {
                    CryptoUtils.ZeroMemory(blob);
                }
                return true;
            }
            finally
            {
                if (pkcs12 != null)
                {
                    CryptoUtils.ZeroMemory(pkcs12);
                }
                if (passcodeBytes != null)
                {
                    CryptoUtils.ZeroMemory(passcodeBytes);
                }
                Array.Clear(passcode, 0, passcode.Length);
            }
        }

        /// <inheritdoc/>
        public async ValueTask<Certificate?> TryTakeAsync(
            PendingCertificateKeyContext context,
            CancellationToken cancellationToken = default)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            string key = KeyFor(context);
            (bool found, ByteString value) = await m_store
                .TryGetAsync(key, cancellationToken)
                .ConfigureAwait(false);
            if (!found || value.IsNull || value.Length == 0)
            {
                return null;
            }

            // Fail-closed: a record that is missing its envelope, fails the
            // integrity check, or was produced under a different key is treated
            // as absent and left in place for an operator to investigate.
            //
            // TryUnprotectOwned hands back a caller-owned plaintext buffer that is
            // always independent of the shared-store input: for a real protector
            // it is the distinct decrypted buffer, and for the pass-through
            // protector it is a fresh copy. Wiping that single buffer in the
            // finally therefore erases the private-key material without ever
            // mutating the store's input buffer (which the pass-through protector
            // would otherwise alias) and without leaving a second, unwipeable
            // copy behind.
            byte[] plainBytes;
            if (m_protector is IOwnedRecordProtector ownedProtector)
            {
                if (!ownedProtector.TryUnprotectOwned(value, out plainBytes))
                {
                    return null;
                }
            }
            else if (m_protector.TryUnprotect(value, out ByteString plaintext))
            {
                plainBytes = plaintext.ToArray();
            }
            else
            {
                return null;
            }

            try
            {
                if (!TryLocateRecord(plainBytes, out int passcodeOffset, out int passcodeLength,
                    out int pkcs12Offset, out int pkcs12Length))
                {
                    return null;
                }

                // Claim the entry atomically: swap the value to an empty
                // tombstone only if it is unchanged, so exactly one replica
                // consumes a pending key even under a cross-replica race.
                bool claimed = await m_store
                    .CompareAndSwapAsync(key, value, ByteString.Empty, cancellationToken)
                    .ConfigureAwait(false);
                if (!claimed)
                {
                    return null;
                }

                await m_store.DeleteAsync(key, cancellationToken).ConfigureAwait(false);

                return ImportCertificate(
                    plainBytes, passcodeOffset, passcodeLength, pkcs12Offset, pkcs12Length);
            }
            finally
            {
                CryptoUtils.ZeroMemory(plainBytes);
            }
        }

        /// <inheritdoc/>
        public ValueTask RemoveAsync(
            PendingCertificateKeyContext context,
            CancellationToken cancellationToken = default)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            ValueTask<bool> delete = m_store.DeleteAsync(KeyFor(context), cancellationToken);
            return delete.IsCompletedSuccessfully ? default : AwaitDeleteAsync(delete);
        }

        /// <summary>
        /// Computes the shared-store key for a pending-key scope: the configured
        /// prefix followed by a stable digest of the (certificate group,
        /// certificate type) pair, so the raw NodeIds never appear verbatim in
        /// the keyspace.
        /// </summary>
        /// <param name="context">The pending-key scope.</param>
        /// <returns>The opaque store key.</returns>
        internal string KeyFor(PendingCertificateKeyContext context)
        {
            return m_prefix + ComputeScope(context.CertificateGroupId, context.CertificateTypeId);
        }

        private static async ValueTask AwaitDeleteAsync(ValueTask<bool> delete)
        {
            await delete.ConfigureAwait(false);
        }

        private static Certificate ImportCertificate(
            byte[] record,
            int passcodeOffset,
            int passcodeLength,
            int pkcs12Offset,
            int pkcs12Length)
        {
            byte[] pkcs12 = new byte[pkcs12Length];
            char[]? passcode = null;
            try
            {
                Buffer.BlockCopy(record, pkcs12Offset, pkcs12, 0, pkcs12Length);
                passcode = Encoding.UTF8.GetChars(record, passcodeOffset, passcodeLength);
                return new Certificate(pkcs12, passcode, X509KeyStorageFlags.Exportable);
            }
            finally
            {
                CryptoUtils.ZeroMemory(pkcs12);
                if (passcode != null)
                {
                    Array.Clear(passcode, 0, passcode.Length);
                }
            }
        }

        private static byte[] EncodeRecord(byte[] passcode, byte[] pkcs12)
        {
            byte[] buffer = new byte[4 + passcode.Length + 4 + pkcs12.Length];
            BinaryPrimitives.WriteInt32LittleEndian(buffer.AsSpan(0, 4), passcode.Length);
            Buffer.BlockCopy(passcode, 0, buffer, 4, passcode.Length);
            BinaryPrimitives.WriteInt32LittleEndian(
                buffer.AsSpan(4 + passcode.Length, 4), pkcs12.Length);
            Buffer.BlockCopy(pkcs12, 0, buffer, 4 + passcode.Length + 4, pkcs12.Length);
            return buffer;
        }

        private static bool TryLocateRecord(
            byte[] record,
            out int passcodeOffset,
            out int passcodeLength,
            out int pkcs12Offset,
            out int pkcs12Length)
        {
            passcodeOffset = 0;
            passcodeLength = 0;
            pkcs12Offset = 0;
            pkcs12Length = 0;
            if (record.Length < 8)
            {
                return false;
            }

            int pwdLen = BinaryPrimitives.ReadInt32LittleEndian(record.AsSpan(0, 4));
            if (pwdLen < 0 || 4L + pwdLen + 4 > record.Length)
            {
                return false;
            }

            int keyLenOffset = 4 + pwdLen;
            int keyLen = BinaryPrimitives.ReadInt32LittleEndian(record.AsSpan(keyLenOffset, 4));
            if (keyLen <= 0 || (long)keyLenOffset + 4 + keyLen > record.Length)
            {
                return false;
            }

            passcodeOffset = 4;
            passcodeLength = pwdLen;
            pkcs12Offset = keyLenOffset + 4;
            pkcs12Length = keyLen;
            return true;
        }

        private static string ComputeScope(NodeId certificateGroupId, NodeId certificateTypeId)
        {
            string key = certificateGroupId.ToString() + "|" + certificateTypeId.ToString();
            byte[] keyBytes = Encoding.UTF8.GetBytes(key);
#if NET8_0_OR_GREATER
            byte[] hash = SHA256.HashData(keyBytes);
#else
            byte[] hash;
            using (SHA256 sha256 = SHA256.Create())
            {
                hash = sha256.ComputeHash(keyBytes);
            }
#endif
            return Utils.ToHexString(hash)[..16];
        }

        private static char[] GeneratePasscode()
        {
            byte[] tokenBuffer = Nonce.CreateRandomNonceData(24);
            // Base64 expands by 4/3; size the output buffer from the actual
            // token length (Nonce may enforce a larger minimum) with headroom.
            char[] charToken = new char[tokenBuffer.Length * 2];
            try
            {
                int written = Convert.ToBase64CharArray(
                    tokenBuffer, 0, tokenBuffer.Length, charToken, 0, Base64FormattingOptions.None);
                char[] passcode = new char[written];
                Array.Copy(charToken, passcode, written);
                return passcode;
            }
            finally
            {
                CryptoUtils.ZeroMemory(tokenBuffer);
                Array.Clear(charToken, 0, charToken.Length);
            }
        }

        private readonly ISharedKeyValueStore m_store;
        private readonly string m_prefix;
        private readonly IRecordProtector m_protector;
    }
}
