//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opc.Ua.Gds.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ApplicationNames = new HashSet<ApplicationName>();
            this.ServerEndpoints = new HashSet<ServerEndpoint>();
            this.CertificateRequests = new HashSet<CertificateRequest>();
        }
    
        public int ID { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string ApplicationUri { get; set; }
        public string ApplicationName { get; set; }
        public int ApplicationType { get; set; }
        public string ProductUri { get; set; }
        public string ServerCapabilities { get; set; }
        public byte[] Certificate { get; set; }
        public byte[] HttpsCertificate { get; set; }
        public Nullable<int> TrustListId { get; set; }
        public Nullable<int> HttpsTrustListId { get; set; }
    
        public virtual ICollection<ApplicationName> ApplicationNames { get; set; }
        public virtual ICollection<ServerEndpoint> ServerEndpoints { get; set; }
        public virtual CertificateStore HttpsTrustList { get; set; }
        public virtual CertificateStore TrustList { get; set; }
        public virtual ICollection<CertificateRequest> CertificateRequests { get; set; }
    }
}
