/* ========================================================================
 * Copyright (c) 2005-2026 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.IO;
using Opc.Ua.SchemaRegistry;
using Opc.Ua.XRegistry;

namespace Opc.Ua.EndpointRegistry
{
    /// <summary>
    /// The published native catalog of the Endpoint Registry: every Endpoint, Message Group, Message,
    /// protocol, envelope and media record with its source members, selector families and maps.
    /// </summary>
    /// <remarks>
    /// The tables are generated by <c>tools/GenerateRegistryNativeCatalog.py</c> from the specification's
    /// native catalog and checked in; provenance is recorded in <c>tools/registry-native-catalog.json</c>.
    /// The root <see cref="EndpointRegistryDocumentDataType"/> contains the Endpoint and Message Group maps,
    /// Endpoints and Message Groups contain Messages and a Message contains its optional Versions.
    /// Inline schema content is owned by a <see cref="SchemaContentValueAdapter"/>.
    /// </remarks>
    public static partial class EndpointRegistryNativeCatalog
    {
        /// <summary>
        /// Gets the published Endpoint Registry catalog.
        /// </summary>
        public static RegistryNativeCatalog Catalog => s_catalog.Value;

        /// <summary>
        /// Creates a builder that contains the Endpoint Registry catalog, for example to register a vendor
        /// selector subtype with <see cref="RegistryNativeCatalog.Builder.RegisterChoice"/>.
        /// </summary>
        public static RegistryNativeCatalog.Builder CreateBuilder()
        {
            RegistryNativeCatalog.Builder builder = RegistrySharedNativeCatalog.CreateBuilder();
            AddGeneratedTypes(builder);
            return builder;
        }

        /// <summary>
        /// Creates a mapper for Endpoint Registry documents. Inline JSON Schema and Avro content is mapped
        /// through the supplied schema format providers; a format without a provider is rejected explicitly.
        /// </summary>
        public static RegistryRecordMapper CreateMapper(
            IServiceMessageContext context,
            ArrayOf<ISchemaFormatProvider> schemaFormats)
        {
            return new RegistryRecordMapper(Catalog, context, [new SchemaContentValueAdapter(schemaFormats)]);
        }

        /// <summary>
        /// Reads the locally composed and pinned model as complete generic native values.
        /// No model include is fetched or inferred at runtime.
        /// </summary>
        public static RegistryObjectValueDataType ReadModel(bool media = false)
        {
            using Stream source = NativeJsonSchemaSet.OpenResource(media
                ? "composed-media-model.json" : "resolved-endpoint-model.json");
            using var bytes = new MemoryStream();
            source.CopyTo(bytes);
            return RegistryValues.Parse(bytes.ToArray()) is RegistryObjectValueDataType document
                ? document
                : throw new InvalidOperationException("The embedded registry model is not an object.");
        }

        private static RegistryNativeTypeDescriptor Native(
            string name,
            ExpandedNodeId dataTypeId,
            string baseType,
            bool isAbstract,
            Func<IEncodeable>? factory,
            params RegistryNativeFieldDescriptor[] fields)
        {
            return new RegistryNativeTypeDescriptor(name, dataTypeId, baseType)
            {
                IsAbstract = isAbstract,
                Factory = factory,
                Fields = fields
            };
        }

        private static RegistryNativeTypeDescriptor Adapter(
            string name,
            ExpandedNodeId dataTypeId,
            string baseType,
            bool isAbstract,
            Func<IEncodeable>? factory)
        {
            return new RegistryNativeTypeDescriptor(name, dataTypeId, baseType)
            {
                IsAbstract = isAbstract,
                Factory = factory
            };
        }

        private static RegistryNativeFieldDescriptor Field(
            string name,
            string dataType,
            string source,
            bool isArray,
            bool allowSubtypes,
            RegistrySourceShape? shape)
        {
            return new RegistryNativeFieldDescriptor(name, dataType)
            {
                Source = source,
                IsArray = isArray,
                AllowSubtypes = allowSubtypes,
                Shape = shape
            };
        }

        private static readonly Lazy<RegistryNativeCatalog> s_catalog = new(() => CreateBuilder().Build());
    }
}
