// <auto-generated>
// Generated by tools/GenerateRegistryNativeCatalog.py. Do not edit; regenerate from the pinned
// specification catalog instead. Provenance (also recorded in tools/registry-native-catalog.json):
//   repository: OPCF-Members/OPC30450-CloudInitiative
//   commit: 31e3efd979bf9a356449e59bec75796069b577cb
//   uncommittedSource: false
//   catalog: 80a33dbaf36ab30cdd8267ab18984e8310e5ab6d83386dad2a25ba3045fdb637
//   Endpoint coverage rows: 418 (committed ledger matches: true)
// </auto-generated>

using Opc.Ua.XRegistry;

namespace Opc.Ua.EndpointRegistry
{
    public static partial class EndpointRegistryNativeCatalog
    {
        private static void AddGeneratedTypes(RegistryNativeCatalog.Builder builder)
        {
            builder.AddType(Adapter("SchemaContentDataType", global::Opc.Ua.SchemaRegistry.DataTypeIds.SchemaContentDataType, "Structure", true, null));
            builder.AddType(Adapter("JsonSchemaContentDataType", global::Opc.Ua.SchemaRegistry.DataTypeIds.JsonSchemaContentDataType, "SchemaContentDataType", false, static () => new global::Opc.Ua.SchemaRegistry.JsonSchemaContentDataType()));
            builder.AddType(Adapter("AvroSchemaContentDataType", global::Opc.Ua.SchemaRegistry.DataTypeIds.AvroSchemaContentDataType, "SchemaContentDataType", false, static () => new global::Opc.Ua.SchemaRegistry.AvroSchemaContentDataType()));
            builder.AddType(Adapter("ArrowSchemaContentDataType", global::Opc.Ua.SchemaRegistry.DataTypeIds.ArrowSchemaContentDataType, "SchemaContentDataType", false, static () => new global::Opc.Ua.SchemaRegistry.ArrowSchemaContentDataType()));
            builder.AddType(Adapter("ExtensionSchemaContentDataType", global::Opc.Ua.SchemaRegistry.DataTypeIds.ExtensionSchemaContentDataType, "SchemaContentDataType", false, static () => new global::Opc.Ua.SchemaRegistry.ExtensionSchemaContentDataType()));
            builder.AddType(Adapter("ArrowIpcSchemaContentDataType", global::Opc.Ua.SchemaRegistry.DataTypeIds.ArrowIpcSchemaContentDataType, "SchemaContentDataType", false, static () => new global::Opc.Ua.SchemaRegistry.ArrowIpcSchemaContentDataType()));
            builder.AddType(Native("MessageDefinitionLabelsEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionLabelsEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionLabelsEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "String", "", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionLabelsDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionLabelsDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionLabelsDataType()
                , Field("Entries", "MessageDefinitionLabelsEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataSpecVersionDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataSpecVersionDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeMetadataSpecVersionDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataIdDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataIdDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeMetadataIdDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataTypeDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataTypeDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeMetadataTypeDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataSourceDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataSourceDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeMetadataSourceDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataSubjectDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataSubjectDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeMetadataSubjectDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataTimeDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataTimeDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeMetadataTimeDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataDataSchemaDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataDataSchemaDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeMetadataDataSchemaDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataDataContentTypeDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataDataContentTypeDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeMetadataDataContentTypeDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataDataType, "RegistryRecordDataType", true, null
                , Field("SpecVersion", "MessageDefinitionEnvelopeMetadataSpecVersionDataType", "specversion", false, true, null)
                , Field("Id", "MessageDefinitionEnvelopeMetadataIdDataType", "id", false, true, null)
                , Field("Type", "MessageDefinitionEnvelopeMetadataTypeDataType", "type", false, true, null)
                , Field("Source", "MessageDefinitionEnvelopeMetadataSourceDataType", "source", false, true, null)
                , Field("Subject", "MessageDefinitionEnvelopeMetadataSubjectDataType", "subject", false, true, null)
                , Field("Time", "MessageDefinitionEnvelopeMetadataTimeDataType", "time", false, true, null)
                , Field("DataSchema", "MessageDefinitionEnvelopeMetadataDataSchemaDataType", "dataschema", false, true, null)
                , Field("DataContentType", "MessageDefinitionEnvelopeMetadataDataContentTypeDataType", "datacontenttype", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataCloudEvents10DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataCloudEvents10DataType, "MessageDefinitionEnvelopeMetadataDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeMetadataCloudEvents10DataType()
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeMetadataExtensionDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeMetadataExtensionDataType, "MessageDefinitionEnvelopeMetadataDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeMetadataExtensionDataType()
                , Field("ExtensionValue", "RegistryValueDataType", "", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeOptionsDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeOptionsDataType, "RegistryRecordDataType", true, null
                , Field("Mode", "String", "mode", false, false, null)
                , Field("Format", "String", "format", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeOptionsCloudEvents10DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeOptionsCloudEvents10DataType, "MessageDefinitionEnvelopeOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeOptionsCloudEvents10DataType()
            ));
            builder.AddType(Native("MessageDefinitionEnvelopeOptionsExtensionDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionEnvelopeOptionsExtensionDataType, "MessageDefinitionEnvelopeOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionEnvelopeOptionsExtensionDataType()
                , Field("ExtensionValue", "RegistryValueDataType", "", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsDataType, "RegistryRecordDataType", true, null
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesMessageIdDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesMessageIdDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesMessageIdDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesUserIdDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesUserIdDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesUserIdDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesToDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesToDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesToDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesSubjectDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesSubjectDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesSubjectDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesReplyToDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesReplyToDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesReplyToDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesCorrelationIdDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesCorrelationIdDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesCorrelationIdDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesContentTypeDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesContentTypeDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesContentTypeDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesContentEncodingDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesContentEncodingDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesContentEncodingDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesAbsoluteExpiryTimeDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesAbsoluteExpiryTimeDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesAbsoluteExpiryTimeDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesCreationTimeDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesCreationTimeDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesCreationTimeDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesGroupIdDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesGroupIdDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesGroupIdDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesGroupSequenceDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesGroupSequenceDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesGroupSequenceDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesReplyToGroupIdDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesReplyToGroupIdDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesReplyToGroupIdDataType()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10PropertiesDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10PropertiesDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10PropertiesDataType()
                , Field("MessageId", "MessageDefinitionProtocolOptionsAMQP10PropertiesMessageIdDataType", "message-id", false, true, null)
                , Field("UserId", "MessageDefinitionProtocolOptionsAMQP10PropertiesUserIdDataType", "user-id", false, true, null)
                , Field("To", "MessageDefinitionProtocolOptionsAMQP10PropertiesToDataType", "to", false, true, null)
                , Field("Subject", "MessageDefinitionProtocolOptionsAMQP10PropertiesSubjectDataType", "subject", false, true, null)
                , Field("ReplyTo", "MessageDefinitionProtocolOptionsAMQP10PropertiesReplyToDataType", "reply-to", false, true, null)
                , Field("CorrelationId", "MessageDefinitionProtocolOptionsAMQP10PropertiesCorrelationIdDataType", "correlation-id", false, true, null)
                , Field("ContentType", "MessageDefinitionProtocolOptionsAMQP10PropertiesContentTypeDataType", "content-type", false, true, null)
                , Field("ContentEncoding", "MessageDefinitionProtocolOptionsAMQP10PropertiesContentEncodingDataType", "content-encoding", false, true, null)
                , Field("AbsoluteExpiryTime", "MessageDefinitionProtocolOptionsAMQP10PropertiesAbsoluteExpiryTimeDataType", "absolute-expiry-time", false, true, null)
                , Field("CreationTime", "MessageDefinitionProtocolOptionsAMQP10PropertiesCreationTimeDataType", "creation-time", false, true, null)
                , Field("GroupId", "MessageDefinitionProtocolOptionsAMQP10PropertiesGroupIdDataType", "group-id", false, true, null)
                , Field("GroupSequence", "MessageDefinitionProtocolOptionsAMQP10PropertiesGroupSequenceDataType", "group-sequence", false, true, null)
                , Field("ReplyToGroupId", "MessageDefinitionProtocolOptionsAMQP10PropertiesReplyToGroupIdDataType", "reply-to-group-id", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesDataTypeValue", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesDataTypeValue, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesDataTypeValue()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesDataTypeValue", "", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesDataType()
                , Field("Entries", "MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsDataTypeValue", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsDataTypeValue, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsDataTypeValue()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsDataTypeValue", "", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsDataType()
                , Field("Entries", "MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsDataTypeValue", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsDataTypeValue, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsDataTypeValue()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsDataTypeValue", "", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsDataType()
                , Field("Entries", "MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10HeaderDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10HeaderDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10HeaderDataType()
                , Field("Durable", "Boolean", "durable", false, false, null)
                , Field("Priority", "RegistryNumberValueDataType", "priority", false, true, new RegistrySourceShape("integer"))
                , Field("Ttl", "RegistryNumberValueDataType", "ttl", false, true, new RegistrySourceShape("integer"))
                , Field("FirstAcquirer", "Boolean", "first-acquirer", false, false, null)
                , Field("DeliveryCount", "RegistryNumberValueDataType", "delivery-count", false, true, new RegistrySourceShape("integer"))
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10FooterDataTypeValue", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10FooterDataTypeValue, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10FooterDataTypeValue()
                , Field("Description", "String", "description", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10FooterEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10FooterEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10FooterEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "MessageDefinitionProtocolOptionsAMQP10FooterDataTypeValue", "", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10FooterDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10FooterDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10FooterDataType()
                , Field("Entries", "MessageDefinitionProtocolOptionsAMQP10FooterEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsAMQP10DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsAMQP10DataType, "MessageDefinitionProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsAMQP10DataType()
                , Field("Properties", "MessageDefinitionProtocolOptionsAMQP10PropertiesDataType", "properties", false, true, null)
                , Field("ApplicationProperties", "MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesDataType", "application-properties", false, true, null)
                , Field("MessageAnnotations", "MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsDataType", "message-annotations", false, true, null)
                , Field("DeliveryAnnotations", "MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsDataType", "delivery-annotations", false, true, null)
                , Field("Header", "MessageDefinitionProtocolOptionsAMQP10HeaderDataType", "header", false, true, null)
                , Field("Footer", "MessageDefinitionProtocolOptionsAMQP10FooterDataType", "footer", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsMQTT311DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsMQTT311DataType, "MessageDefinitionProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsMQTT311DataType()
                , Field("Qos", "RegistryNumberValueDataType", "qos", false, true, new RegistrySourceShape("integer"))
                , Field("Retain", "Boolean", "retain", false, false, null)
                , Field("TopicName", "String", "topic_name", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsMQTT50UserPropertiesDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsMQTT50UserPropertiesDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsMQTT50UserPropertiesDataTypeItem()
                , Field("Name", "String", "name", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Value", "String", "value", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsMQTT50DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsMQTT50DataType, "MessageDefinitionProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsMQTT50DataType()
                , Field("Qos", "RegistryNumberValueDataType", "qos", false, true, new RegistrySourceShape("integer"))
                , Field("Retain", "Boolean", "retain", false, false, null)
                , Field("TopicName", "String", "topic_name", false, false, null)
                , Field("PayloadFormatIndicator", "RegistryNumberValueDataType", "payload_format_indicator", false, true, new RegistrySourceShape("integer"))
                , Field("MessageExpiryInterval", "RegistryNumberValueDataType", "message_expiry_interval", false, true, new RegistrySourceShape("integer"))
                , Field("ResponseTopic", "String", "response_topic", false, false, null)
                , Field("CorrelationData", "String", "correlation_data", false, false, null)
                , Field("ContentType", "String", "content_type", false, false, null)
                , Field("UserProperties", "MessageDefinitionProtocolOptionsMQTT50UserPropertiesDataTypeItem", "user_properties", true, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsKAFKAHeadersDataTypeValue", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsKAFKAHeadersDataTypeValue, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsKAFKAHeadersDataTypeValue()
                , Field("Name", "String", "name", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsKAFKAHeadersEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsKAFKAHeadersEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsKAFKAHeadersEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "MessageDefinitionProtocolOptionsKAFKAHeadersDataTypeValue", "", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsKAFKAHeadersDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsKAFKAHeadersDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsKAFKAHeadersDataType()
                , Field("Entries", "MessageDefinitionProtocolOptionsKAFKAHeadersEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsKAFKADataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsKAFKADataType, "MessageDefinitionProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsKAFKADataType()
                , Field("Topic", "String", "topic", false, false, null)
                , Field("Partition", "RegistryNumberValueDataType", "partition", false, true, new RegistrySourceShape("integer"))
                , Field("Key", "String", "key", false, false, null)
                , Field("KeyBase64", "String", "key_base64", false, false, null)
                , Field("Headers", "MessageDefinitionProtocolOptionsKAFKAHeadersDataType", "headers", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsHTTPHeadersDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsHTTPHeadersDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsHTTPHeadersDataTypeItem()
                , Field("Name", "String", "name", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsHTTPQueryDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsHTTPQueryDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsHTTPQueryDataTypeItem()
                , Field("Name", "String", "name", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsHTTPDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsHTTPDataType, "MessageDefinitionProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsHTTPDataType()
                , Field("Headers", "MessageDefinitionProtocolOptionsHTTPHeadersDataTypeItem", "headers", true, true, null)
                , Field("Query", "MessageDefinitionProtocolOptionsHTTPQueryDataTypeItem", "query", true, true, null)
                , Field("Path", "String", "path", false, false, null)
                , Field("Method", "String", "method", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsNATSHeadersDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsNATSHeadersDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsNATSHeadersDataTypeItem()
                , Field("Name", "String", "name", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Value", "String", "value", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsNATSDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsNATSDataType, "MessageDefinitionProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsNATSDataType()
                , Field("Subject", "String", "subject", false, false, null)
                , Field("Reply", "String", "reply", false, false, null)
                , Field("Headers", "MessageDefinitionProtocolOptionsNATSHeadersDataTypeItem", "headers", true, true, null)
            ));
            builder.AddType(Native("MessageDefinitionProtocolOptionsExtensionDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionProtocolOptionsExtensionDataType, "MessageDefinitionProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionProtocolOptionsExtensionDataType()
                , Field("ExtensionValue", "RegistryValueDataType", "", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionDataType()
                , Field("Name", "String", "name", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Documentation", "String", "documentation", false, false, null)
                , Field("Self", "String", "self", false, false, null)
                , Field("Xid", "String", "xid", false, false, null)
                , Field("CreatedAt", "String", "createdat", false, false, null)
                , Field("ModifiedAt", "String", "modifiedat", false, false, null)
                , Field("Deprecated", "String", "deprecated", false, false, null)
                , Field("Epoch", "RegistryNumberValueDataType", "epoch", false, true, new RegistrySourceShape("uinteger"))
                , Field("Labels", "MessageDefinitionLabelsDataType", "labels", false, true, null)
                , Field("MessageId", "String", "messageid", false, false, null)
                , Field("VersionId", "String", "versionid", false, false, null)
                , Field("BaseMessageUri", "String", "basemessageuri", false, false, null)
                , Field("Envelope", "String", "envelope", false, false, null)
                , Field("Protocol", "String", "protocol", false, false, null)
                , Field("DataSchemaFormat", "String", "dataschemaformat", false, false, null)
                , Field("DataSchema", "SchemaContentDataType", "dataschema", false, true, null)
                , Field("DataSchemaUri", "String", "dataschemauri", false, false, null)
                , Field("DataSchemaXid", "String", "dataschemaxid", false, false, null)
                , Field("DataContentType", "String", "datacontenttype", false, false, null)
                , Field("EnvelopeMetadata", "MessageDefinitionEnvelopeMetadataDataType", "envelopemetadata", false, true, null)
                , Field("EnvelopeOptions", "MessageDefinitionEnvelopeOptionsDataType", "envelopeoptions", false, true, null)
                , Field("ProtocolOptions", "MessageDefinitionProtocolOptionsDataType", "protocoloptions", false, true, null)
                , Field("Versions", "MessageDefinitionMapDataType", "versions", false, true, null)
                , Field("Versionscount", "RegistryValueDataType", "versionscount", false, true, null)
                , Field("Hasdocument", "Boolean", "hasdocument", false, false, null)
                , Field("Maxversions", "RegistryValueDataType", "maxversions", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionMapEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionMapEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionMapEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "MessageDefinitionDataType", "", false, true, null)
            ));
            builder.AddType(Native("MessageDefinitionMapDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageDefinitionMapDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageDefinitionMapDataType()
                , Field("Entries", "MessageDefinitionMapEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("MessageGroupMapEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageGroupMapEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageGroupMapEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "MessageGroupDataType", "", false, true, null)
            ));
            builder.AddType(Native("MessageGroupMapDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageGroupMapDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageGroupMapDataType()
                , Field("Entries", "MessageGroupMapEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("EndpointGroupMapEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointGroupMapEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointGroupMapEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "EndpointDataType", "", false, true, null)
            ));
            builder.AddType(Native("EndpointGroupMapDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointGroupMapDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointGroupMapDataType()
                , Field("Entries", "EndpointGroupMapEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("MessageGroupLabelsEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageGroupLabelsEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageGroupLabelsEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "String", "", false, false, null)
            ));
            builder.AddType(Native("MessageGroupLabelsDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageGroupLabelsDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.MessageGroupLabelsDataType()
                , Field("Entries", "MessageGroupLabelsEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("MessageGroupDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.MessageGroupDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.MessageGroupDataType()
                , Field("Name", "String", "name", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Documentation", "String", "documentation", false, false, null)
                , Field("Self", "String", "self", false, false, null)
                , Field("Xid", "String", "xid", false, false, null)
                , Field("CreatedAt", "String", "createdat", false, false, null)
                , Field("ModifiedAt", "String", "modifiedat", false, false, null)
                , Field("Deprecated", "String", "deprecated", false, false, null)
                , Field("Epoch", "RegistryNumberValueDataType", "epoch", false, true, new RegistrySourceShape("uinteger"))
                , Field("Labels", "MessageGroupLabelsDataType", "labels", false, true, null)
                , Field("MessageGroupId", "String", "messagegroupid", false, false, null)
                , Field("Envelope", "String", "envelope", false, false, null)
                , Field("Protocol", "String", "protocol", false, false, null)
                , Field("Messages", "MessageDefinitionMapDataType", "messages", false, true, null)
                , Field("Messagescount", "RegistryValueDataType", "messagescount", false, true, null)
                , Field("Messagesurl", "String", "messagesurl", false, false, null)
            ));
            builder.AddType(Native("EndpointDeprecatedDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointDeprecatedDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointDeprecatedDataType()
                , Field("Effective", "String", "effective", false, false, null)
                , Field("Removal", "String", "removal", false, false, null)
                , Field("Alternative", "String", "alternative", false, false, null)
                , Field("Docs", "String", "docs", false, false, null)
            ));
            builder.AddType(Native("EndpointLabelsEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointLabelsEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointLabelsEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "String", "", false, false, null)
            ));
            builder.AddType(Native("EndpointLabelsDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointLabelsDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointLabelsDataType()
                , Field("Entries", "EndpointLabelsEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("EndpointEnvelopeOptionsDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointEnvelopeOptionsDataType, "RegistryRecordDataType", true, null
                , Field("Mode", "String", "mode", false, false, null)
                , Field("Format", "String", "format", false, false, null)
            ));
            builder.AddType(Native("EndpointEnvelopeOptionsCloudEvents10DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointEnvelopeOptionsCloudEvents10DataType, "EndpointEnvelopeOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointEnvelopeOptionsCloudEvents10DataType()
            ));
            builder.AddType(Native("EndpointEnvelopeOptionsExtensionDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointEnvelopeOptionsExtensionDataType, "EndpointEnvelopeOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointEnvelopeOptionsExtensionDataType()
                , Field("ExtensionValue", "RegistryValueDataType", "", false, true, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsAuthorizationDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsAuthorizationDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsAuthorizationDataTypeItem()
                , Field("Type", "String", "type", false, false, null)
                , Field("Mechanism", "String", "mechanism", false, false, null)
                , Field("Resourceuri", "String", "resourceuri", false, false, null)
                , Field("Authorityuri", "String", "authorityuri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsDataType, "RegistryRecordDataType", true, null
                , Field("Authorization", "EndpointProtocolOptionsAuthorizationDataTypeItem", "authorization", true, true, null)
                , Field("Deployed", "Boolean", "deployed", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsAMQP10EndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsAMQP10EndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsAMQP10EndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsAMQP10LinkPropertiesEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsAMQP10LinkPropertiesEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsAMQP10LinkPropertiesEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "String", "", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsAMQP10LinkPropertiesDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsAMQP10LinkPropertiesDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsAMQP10LinkPropertiesDataType()
                , Field("Entries", "EndpointProtocolOptionsAMQP10LinkPropertiesEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsAMQP10ConnectionPropertiesEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsAMQP10ConnectionPropertiesEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsAMQP10ConnectionPropertiesEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "String", "", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsAMQP10ConnectionPropertiesDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsAMQP10ConnectionPropertiesDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsAMQP10ConnectionPropertiesDataType()
                , Field("Entries", "EndpointProtocolOptionsAMQP10ConnectionPropertiesEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsAMQP10SourceFiltersEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsAMQP10SourceFiltersEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsAMQP10SourceFiltersEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "RegistryValueDataType", "", false, true, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsAMQP10SourceFiltersDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsAMQP10SourceFiltersDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsAMQP10SourceFiltersDataType()
                , Field("Entries", "EndpointProtocolOptionsAMQP10SourceFiltersEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsAMQP10DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsAMQP10DataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsAMQP10DataType()
                , Field("Endpoints", "EndpointProtocolOptionsAMQP10EndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("Node", "String", "node", false, false, null)
                , Field("Durable", "Boolean", "durable", false, false, null)
                , Field("LinkProperties", "EndpointProtocolOptionsAMQP10LinkPropertiesDataType", "link-properties", false, true, null)
                , Field("ConnectionProperties", "EndpointProtocolOptionsAMQP10ConnectionPropertiesDataType", "connection-properties", false, true, null)
                , Field("DistributionMode", "String", "distribution-mode", false, false, null)
                , Field("ConnectionCapabilities", "String", "connection-capabilities", true, false, null)
                , Field("NodeCapabilities", "String", "node-capabilities", true, false, null)
                , Field("SourceFilters", "EndpointProtocolOptionsAMQP10SourceFiltersDataType", "source-filters", false, true, null)
                , Field("Dynamic", "Boolean", "dynamic", false, false, null)
                , Field("TerminusDurability", "String", "terminus-durability", false, false, null)
                , Field("ExpiryPolicy", "String", "expiry-policy", false, false, null)
                , Field("Timeout", "RegistryNumberValueDataType", "timeout", false, true, new RegistrySourceShape("uinteger"))
                , Field("SenderSettleMode", "String", "sender-settle-mode", false, false, null)
                , Field("ReceiverSettleMode", "String", "receiver-settle-mode", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsMQTT50EndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsMQTT50EndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsMQTT50EndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsMQTT50DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsMQTT50DataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsMQTT50DataType()
                , Field("Endpoints", "EndpointProtocolOptionsMQTT50EndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("Topic", "String", "topic", false, false, null)
                , Field("Qos", "RegistryNumberValueDataType", "qos", false, true, new RegistrySourceShape("uinteger"))
                , Field("Retain", "Boolean", "retain", false, false, null)
                , Field("TopicFilter", "String", "topicfilter", false, false, null)
                , Field("CleanStart", "Boolean", "cleanstart", false, false, null)
                , Field("SessionExpiryInterval", "RegistryNumberValueDataType", "sessionexpiryinterval", false, true, new RegistrySourceShape("uinteger"))
                , Field("SharedSubscriptionGroup", "String", "sharedsubscriptiongroup", false, false, null)
                , Field("Nolocal", "Boolean", "nolocal", false, false, null)
                , Field("Retainaspublished", "Boolean", "retainaspublished", false, false, null)
                , Field("Retainhandling", "RegistryNumberValueDataType", "retainhandling", false, true, new RegistrySourceShape("uinteger"))
                , Field("Willtopic", "String", "willtopic", false, false, null)
                , Field("Willmessage", "String", "willmessage", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsMQTT311EndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsMQTT311EndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsMQTT311EndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsMQTT311DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsMQTT311DataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsMQTT311DataType()
                , Field("Endpoints", "EndpointProtocolOptionsMQTT311EndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("Topic", "String", "topic", false, false, null)
                , Field("Qos", "RegistryNumberValueDataType", "qos", false, true, new RegistrySourceShape("uinteger"))
                , Field("Retain", "Boolean", "retain", false, false, null)
                , Field("CleanSession", "Boolean", "cleansession", false, false, null)
                , Field("TopicFilter", "String", "topicfilter", false, false, null)
                , Field("Willtopic", "String", "willtopic", false, false, null)
                , Field("Willmessage", "String", "willmessage", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsHTTPEndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsHTTPEndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsHTTPEndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsHTTPHeadersDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsHTTPHeadersDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsHTTPHeadersDataTypeItem()
                , Field("Name", "String", "name", false, false, null)
                , Field("Value", "String", "value", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsHTTPQueryEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsHTTPQueryEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsHTTPQueryEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "String", "", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsHTTPQueryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsHTTPQueryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsHTTPQueryDataType()
                , Field("Entries", "EndpointProtocolOptionsHTTPQueryEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsHTTPDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsHTTPDataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsHTTPDataType()
                , Field("Endpoints", "EndpointProtocolOptionsHTTPEndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("Method", "String", "method", false, false, null)
                , Field("Headers", "EndpointProtocolOptionsHTTPHeadersDataTypeItem", "headers", true, true, null)
                , Field("Query", "EndpointProtocolOptionsHTTPQueryDataType", "query", false, true, null)
                , Field("Apikeyname", "String", "apikeyname", false, false, null)
                , Field("Apikeyin", "String", "apikeyin", false, false, null)
                , Field("Plainscheme", "String", "plainscheme", false, false, null)
                , Field("Plainusernamefield", "String", "plainusernamefield", false, false, null)
                , Field("Plainpasswordfield", "String", "plainpasswordfield", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsKAFKAEndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsKAFKAEndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsKAFKAEndpointsDataTypeItem()
                , Field("BootstrapServers", "String", "bootstrap.servers", true, false, null)
                , Field("SecurityProtocol", "String", "security.protocol", false, false, null)
                , Field("SaslMechanism", "String", "sasl.mechanism", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsKAFKAHeadersEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsKAFKAHeadersEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsKAFKAHeadersEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "String", "", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsKAFKAHeadersDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsKAFKAHeadersDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsKAFKAHeadersDataType()
                , Field("Entries", "EndpointProtocolOptionsKAFKAHeadersEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsKAFKADataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsKAFKADataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsKAFKADataType()
                , Field("Endpoints", "EndpointProtocolOptionsKAFKAEndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("Topic", "String", "topic", false, false, null)
                , Field("Acks", "RegistryNumberValueDataType", "acks", false, true, new RegistrySourceShape("integer"))
                , Field("Key", "String", "key", false, false, null)
                , Field("Partition", "RegistryNumberValueDataType", "partition", false, true, new RegistrySourceShape("integer"))
                , Field("Consumergroup", "String", "consumergroup", false, false, null)
                , Field("Headers", "EndpointProtocolOptionsKAFKAHeadersDataType", "headers", false, true, null)
                , Field("Keyserializer", "String", "keyserializer", false, false, null)
                , Field("Valueserializer", "String", "valueserializer", false, false, null)
                , Field("Autooffsetreset", "String", "autooffsetreset", false, false, null)
                , Field("Enableautocommit", "Boolean", "enableautocommit", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsNATSEndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsNATSEndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsNATSEndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsNATSDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsNATSDataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsNATSDataType()
                , Field("Endpoints", "EndpointProtocolOptionsNATSEndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("Subject", "String", "subject", false, false, null)
                , Field("Subjectfilter", "String", "subjectfilter", false, false, null)
                , Field("Queuegroup", "String", "queuegroup", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsSRTEndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsSRTEndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsSRTEndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsSRTDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsSRTDataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsSRTDataType()
                , Field("Endpoints", "EndpointProtocolOptionsSRTEndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("Streamid", "String", "streamid", false, false, null)
                , Field("StreamFormat", "String", "streamformat", false, false, null)
                , Field("VideoCodec", "String", "videocodec", false, false, null)
                , Field("AudioCodec", "String", "audiocodec", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsWebRTCEndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsWebRTCEndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsWebRTCEndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsWebRTCDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsWebRTCDataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsWebRTCDataType()
                , Field("Endpoints", "EndpointProtocolOptionsWebRTCEndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("Signaling", "String", "signaling", false, false, null)
                , Field("Signalingreference", "String", "signalingreference", false, false, null)
                , Field("StreamFormat", "String", "streamformat", false, false, null)
                , Field("VideoCodec", "String", "videocodec", false, false, null)
                , Field("AudioCodec", "String", "audiocodec", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRTSP10EndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRTSP10EndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRTSP10EndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRTSP10DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRTSP10DataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRTSP10DataType()
                , Field("Endpoints", "EndpointProtocolOptionsRTSP10EndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("StreamFormat", "String", "streamformat", false, false, null)
                , Field("VideoCodec", "String", "videocodec", false, false, null)
                , Field("AudioCodec", "String", "audiocodec", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRTSP20EndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRTSP20EndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRTSP20EndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRTSP20DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRTSP20DataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRTSP20DataType()
                , Field("Endpoints", "EndpointProtocolOptionsRTSP20EndpointsDataTypeItem", "endpoints", true, true, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRTP2EndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRTP2EndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRTP2EndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRTP2DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRTP2DataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRTP2DataType()
                , Field("Endpoints", "EndpointProtocolOptionsRTP2EndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("Sessiondescription", "String", "sessiondescription", false, false, null)
                , Field("StreamFormat", "String", "streamformat", false, false, null)
                , Field("VideoCodec", "String", "videocodec", false, false, null)
                , Field("AudioCodec", "String", "audiocodec", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsMPEGTSUDPEndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsMPEGTSUDPEndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsMPEGTSUDPEndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsMPEGTSUDPDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsMPEGTSUDPDataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsMPEGTSUDPDataType()
                , Field("Endpoints", "EndpointProtocolOptionsMPEGTSUDPEndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("StreamFormat", "String", "streamformat", false, false, null)
                , Field("VideoCodec", "String", "videocodec", false, false, null)
                , Field("AudioCodec", "String", "audiocodec", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRTMP10EndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRTMP10EndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRTMP10EndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRTMP10DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRTMP10DataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRTMP10DataType()
                , Field("Endpoints", "EndpointProtocolOptionsRTMP10EndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("Application", "String", "application", false, false, null)
                , Field("Streamname", "String", "streamname", false, false, null)
                , Field("StreamFormat", "String", "streamformat", false, false, null)
                , Field("VideoCodec", "String", "videocodec", false, false, null)
                , Field("AudioCodec", "String", "audiocodec", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsHLSEndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsHLSEndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsHLSEndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsHLSDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsHLSDataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsHLSDataType()
                , Field("Endpoints", "EndpointProtocolOptionsHLSEndpointsDataTypeItem", "endpoints", true, true, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsDASHEndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsDASHEndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsDASHEndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsDASHDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsDASHDataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsDASHDataType()
                , Field("Endpoints", "EndpointProtocolOptionsDASHEndpointsDataTypeItem", "endpoints", true, true, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRISTSimple2020EndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRISTSimple2020EndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRISTSimple2020EndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRISTSimple2020DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRISTSimple2020DataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRISTSimple2020DataType()
                , Field("Endpoints", "EndpointProtocolOptionsRISTSimple2020EndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("StreamFormat", "String", "streamformat", false, false, null)
                , Field("VideoCodec", "String", "videocodec", false, false, null)
                , Field("AudioCodec", "String", "audiocodec", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRISTMain2024EndpointsDataTypeItem", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRISTMain2024EndpointsDataTypeItem, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRISTMain2024EndpointsDataTypeItem()
                , Field("Uri", "String", "uri", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsRISTMain2024DataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsRISTMain2024DataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsRISTMain2024DataType()
                , Field("Endpoints", "EndpointProtocolOptionsRISTMain2024EndpointsDataTypeItem", "endpoints", true, true, null)
                , Field("StreamFormat", "String", "streamformat", false, false, null)
                , Field("VideoCodec", "String", "videocodec", false, false, null)
                , Field("AudioCodec", "String", "audiocodec", false, false, null)
            ));
            builder.AddType(Native("EndpointProtocolOptionsExtensionDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointProtocolOptionsExtensionDataType, "EndpointProtocolOptionsDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointProtocolOptionsExtensionDataType()
                , Field("ExtensionValue", "RegistryValueDataType", "", false, true, null)
            ));
            builder.AddType(Native("EndpointDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointDataType()
                , Field("Name", "String", "name", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Documentation", "String", "documentation", false, false, null)
                , Field("Self", "String", "self", false, false, null)
                , Field("Xid", "String", "xid", false, false, null)
                , Field("CreatedAt", "String", "createdat", false, false, null)
                , Field("ModifiedAt", "String", "modifiedat", false, false, null)
                , Field("Deprecated", "EndpointDeprecatedDataType", "deprecated", false, true, null)
                , Field("Epoch", "RegistryNumberValueDataType", "epoch", false, true, new RegistrySourceShape("uinteger"))
                , Field("Labels", "EndpointLabelsDataType", "labels", false, true, null)
                , Field("EndpointId", "String", "endpointid", false, false, null)
                , Field("Usage", "String", "usage", true, false, null)
                , Field("Channel", "String", "channel", false, false, null)
                , Field("Envelope", "String", "envelope", false, false, null)
                , Field("Protocol", "String", "protocol", false, false, null)
                , Field("MessageGroups", "String", "messagegroups", true, false, null)
                , Field("EnvelopeOptions", "EndpointEnvelopeOptionsDataType", "envelopeoptions", false, true, null)
                , Field("ProtocolOptions", "EndpointProtocolOptionsDataType", "protocoloptions", false, true, null)
                , Field("Messages", "MessageDefinitionMapDataType", "messages", false, true, null)
                , Field("Messagescount", "RegistryValueDataType", "messagescount", false, true, null)
                , Field("Messagesurl", "String", "messagesurl", false, false, null)
            ));
            builder.AddType(Native("EndpointRegistryDocumentLabelsEntryDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointRegistryDocumentLabelsEntryDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointRegistryDocumentLabelsEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "String", "", false, false, null)
            ));
            builder.AddType(Native("EndpointRegistryDocumentLabelsDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointRegistryDocumentLabelsDataType, "Structure", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointRegistryDocumentLabelsDataType()
                , Field("Entries", "EndpointRegistryDocumentLabelsEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("EndpointRegistryDocumentDataType", global::Opc.Ua.EndpointRegistry.DataTypeIds.EndpointRegistryDocumentDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.EndpointRegistry.EndpointRegistryDocumentDataType()
                , Field("Name", "String", "name", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Documentation", "String", "documentation", false, false, null)
                , Field("Self", "String", "self", false, false, null)
                , Field("Xid", "String", "xid", false, false, null)
                , Field("CreatedAt", "String", "createdat", false, false, null)
                , Field("ModifiedAt", "String", "modifiedat", false, false, null)
                , Field("Deprecated", "String", "deprecated", false, false, null)
                , Field("Epoch", "RegistryNumberValueDataType", "epoch", false, true, new RegistrySourceShape("uinteger"))
                , Field("Labels", "EndpointRegistryDocumentLabelsDataType", "labels", false, true, null)
                , Field("RegistryId", "String", "registryid", false, false, null)
                , Field("SpecVersion", "String", "specversion", false, false, null)
                , Field("Endpoints", "EndpointGroupMapDataType", "endpoints", false, true, null)
                , Field("Messagegroups", "MessageGroupMapDataType", "messagegroups", false, true, null)
                , Field("Endpointscount", "RegistryValueDataType", "endpointscount", false, true, null)
                , Field("Messagegroupscount", "RegistryValueDataType", "messagegroupscount", false, true, null)
                , Field("Endpointsurl", "String", "endpointsurl", false, false, null)
                , Field("Messagegroupsurl", "String", "messagegroupsurl", false, false, null)
            ));
            builder.AddMap(new RegistryNativeMapDescriptor("EndpointGroupMapDataType", "EndpointGroupMapEntryDataType", "EndpointDataType") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("EndpointLabelsDataType", "EndpointLabelsEntryDataType", "String") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("EndpointProtocolOptionsAMQP10ConnectionPropertiesDataType", "EndpointProtocolOptionsAMQP10ConnectionPropertiesEntryDataType", "String") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("EndpointProtocolOptionsAMQP10LinkPropertiesDataType", "EndpointProtocolOptionsAMQP10LinkPropertiesEntryDataType", "String") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("EndpointProtocolOptionsAMQP10SourceFiltersDataType", "EndpointProtocolOptionsAMQP10SourceFiltersEntryDataType", "RegistryValueDataType") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("EndpointProtocolOptionsHTTPQueryDataType", "EndpointProtocolOptionsHTTPQueryEntryDataType", "String") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("EndpointProtocolOptionsKAFKAHeadersDataType", "EndpointProtocolOptionsKAFKAHeadersEntryDataType", "String") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("EndpointRegistryDocumentLabelsDataType", "EndpointRegistryDocumentLabelsEntryDataType", "String") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("MessageDefinitionLabelsDataType", "MessageDefinitionLabelsEntryDataType", "String") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("MessageDefinitionMapDataType", "MessageDefinitionMapEntryDataType", "MessageDefinitionDataType") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesDataType", "MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesEntryDataType", "MessageDefinitionProtocolOptionsAMQP10ApplicationPropertiesDataTypeValue") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsDataType", "MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsEntryDataType", "MessageDefinitionProtocolOptionsAMQP10DeliveryAnnotationsDataTypeValue") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("MessageDefinitionProtocolOptionsAMQP10FooterDataType", "MessageDefinitionProtocolOptionsAMQP10FooterEntryDataType", "MessageDefinitionProtocolOptionsAMQP10FooterDataTypeValue") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsDataType", "MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsEntryDataType", "MessageDefinitionProtocolOptionsAMQP10MessageAnnotationsDataTypeValue") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("MessageDefinitionProtocolOptionsKAFKAHeadersDataType", "MessageDefinitionProtocolOptionsKAFKAHeadersEntryDataType", "MessageDefinitionProtocolOptionsKAFKAHeadersDataTypeValue") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("MessageGroupLabelsDataType", "MessageGroupLabelsEntryDataType", "String") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("MessageGroupMapDataType", "MessageGroupMapEntryDataType", "MessageGroupDataType") { ValueShape = null });
            builder.AddChoiceFamily(new RegistryNativeChoiceFamily("SchemaContentDataType", "dataschemaformat", "ExtensionSchemaContentDataType")
            {
                Comparison = RegistrySelectorComparison.CaseFold,
                Aliases = [],
                Choices = [new RegistryNativeChoice("JsonSchema/2020-12", "JsonSchemaContentDataType"), new RegistryNativeChoice("Avro/1.11", "AvroSchemaContentDataType"), new RegistryNativeChoice("ApacheArrow/1.0", "ArrowSchemaContentDataType")]
            });
            builder.AddChoiceFamily(new RegistryNativeChoiceFamily("MessageDefinitionEnvelopeMetadataDataType", "envelope", "MessageDefinitionEnvelopeMetadataExtensionDataType")
            {
                Comparison = RegistrySelectorComparison.UpperCase,
                Aliases = [],
                Choices = [new RegistryNativeChoice("CLOUDEVENTS/1.0", "MessageDefinitionEnvelopeMetadataCloudEvents10DataType")]
            });
            builder.AddChoiceFamily(new RegistryNativeChoiceFamily("MessageDefinitionEnvelopeOptionsDataType", "envelope", "MessageDefinitionEnvelopeOptionsExtensionDataType")
            {
                Comparison = RegistrySelectorComparison.UpperCase,
                Aliases = [],
                Choices = [new RegistryNativeChoice("CLOUDEVENTS/1.0", "MessageDefinitionEnvelopeOptionsCloudEvents10DataType")]
            });
            builder.AddChoiceFamily(new RegistryNativeChoiceFamily("MessageDefinitionProtocolOptionsDataType", "protocol", "MessageDefinitionProtocolOptionsExtensionDataType")
            {
                Comparison = RegistrySelectorComparison.UpperCase,
                Aliases = [new RegistrySelectorAlias("AMQP", "AMQP/1.0"), new RegistrySelectorAlias("MQTT", "MQTT/5.0")],
                Choices = [new RegistryNativeChoice("AMQP/1.0", "MessageDefinitionProtocolOptionsAMQP10DataType"), new RegistryNativeChoice("MQTT/3.1.1", "MessageDefinitionProtocolOptionsMQTT311DataType"), new RegistryNativeChoice("MQTT/5.0", "MessageDefinitionProtocolOptionsMQTT50DataType"), new RegistryNativeChoice("KAFKA", "MessageDefinitionProtocolOptionsKAFKADataType"), new RegistryNativeChoice("HTTP", "MessageDefinitionProtocolOptionsHTTPDataType"), new RegistryNativeChoice("NATS", "MessageDefinitionProtocolOptionsNATSDataType")]
            });
            builder.AddChoiceFamily(new RegistryNativeChoiceFamily("EndpointEnvelopeOptionsDataType", "envelope", "EndpointEnvelopeOptionsExtensionDataType")
            {
                Comparison = RegistrySelectorComparison.UpperCase,
                Aliases = [],
                Choices = [new RegistryNativeChoice("CLOUDEVENTS/1.0", "EndpointEnvelopeOptionsCloudEvents10DataType")]
            });
            builder.AddChoiceFamily(new RegistryNativeChoiceFamily("EndpointProtocolOptionsDataType", "protocol", "EndpointProtocolOptionsExtensionDataType")
            {
                Comparison = RegistrySelectorComparison.UpperCase,
                Aliases = [new RegistrySelectorAlias("AMQP", "AMQP/1.0"), new RegistrySelectorAlias("MQTT", "MQTT/5.0")],
                Choices = [new RegistryNativeChoice("AMQP/1.0", "EndpointProtocolOptionsAMQP10DataType"), new RegistryNativeChoice("MQTT/5.0", "EndpointProtocolOptionsMQTT50DataType"), new RegistryNativeChoice("MQTT/3.1.1", "EndpointProtocolOptionsMQTT311DataType"), new RegistryNativeChoice("HTTP", "EndpointProtocolOptionsHTTPDataType"), new RegistryNativeChoice("KAFKA", "EndpointProtocolOptionsKAFKADataType"), new RegistryNativeChoice("NATS", "EndpointProtocolOptionsNATSDataType"), new RegistryNativeChoice("SRT", "EndpointProtocolOptionsSRTDataType"), new RegistryNativeChoice("WEBRTC", "EndpointProtocolOptionsWebRTCDataType"), new RegistryNativeChoice("RTSP/1.0", "EndpointProtocolOptionsRTSP10DataType"), new RegistryNativeChoice("RTSP/2.0", "EndpointProtocolOptionsRTSP20DataType"), new RegistryNativeChoice("RTP/2", "EndpointProtocolOptionsRTP2DataType"), new RegistryNativeChoice("MPEGTS-UDP", "EndpointProtocolOptionsMPEGTSUDPDataType"), new RegistryNativeChoice("RTMP/1.0", "EndpointProtocolOptionsRTMP10DataType"), new RegistryNativeChoice("HLS", "EndpointProtocolOptionsHLSDataType"), new RegistryNativeChoice("DASH", "EndpointProtocolOptionsDASHDataType"), new RegistryNativeChoice("RIST-SIMPLE/2020", "EndpointProtocolOptionsRISTSimple2020DataType"), new RegistryNativeChoice("RIST-MAIN/2024", "EndpointProtocolOptionsRISTMain2024DataType")]
            });
        }
    }
}
