/* ========================================================================
 * Copyright (c) 2005-2024 The OPC Foundation, Inc. All rights reserved.
 *
 * OPC Foundation MIT License 1.00
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * The complete license agreement can be found here:
 * http://opcfoundation.org/License/MIT/1.00/
 * ======================================================================*/

using System;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Serialization;

namespace Opc.Ua.Schema.Model
{
    public partial class ModelDesign
    {
        /// <summary>
        /// Target namespace information
        /// </summary>
        [XmlIgnore]
        public Namespace TargetNamespaceInfo { get; set; }

        /// <summary>
        /// Namespace table
        /// </summary>
        [XmlIgnore]
#pragma warning disable CA2235 // Mark all non-serializable fields
        public NamespaceTable NamespaceUris { get; set; }
#pragma warning restore CA2235 // Mark all non-serializable fields

        /// <summary>
        /// Source file path
        /// </summary>
        [XmlIgnore]
        public string SourceFilePath { get; set; }

        /// <summary>
        /// Is source node set
        /// </summary>
        [XmlIgnore]
        public bool IsSourceNodeSet { get; set; }

        /// <summary>
        /// Dependencies
        /// </summary>
        [XmlIgnore]
        public Dictionary<string, Export.ModelTableEntry> Dependencies { get; set; }
    }

    public partial class LocalizedText
    {
        /// <summary>
        /// Text is autogenerated
        /// </summary>
        [XmlIgnore]
        public bool IsAutogenerated { get; set; }
    }

    /// <summary>
    /// Hierarchy node information
    /// </summary>
    public class HierarchyNode : IFormattable
    {
        /// <summary>
        /// Relative path
        /// </summary>
        public string RelativePath { get; set; }

        /// <summary>
        /// Instance
        /// </summary>
        public NodeDesign Instance { get; set; }

        /// <summary>
        /// Overridden nodes
        /// </summary>
        public List<NodeDesign> OverriddenNodes { get; set; }

        /// <summary>
        /// Explicitly defined
        /// </summary>
        public bool ExplicitlyDefined { get; set; }

        /// <summary>
        /// Ad hoc instance
        /// </summary>
        public bool AdHocInstance { get; set; }

        /// <summary>
        /// Static value
        /// </summary>
        public bool StaticValue { get; set; }

        /// <summary>
        /// Inherited
        /// </summary>
        public bool Inherited { get; set; }

        /// <summary>
        /// Identifier
        /// </summary>
        public object Identifier { get; set; }

        /// <summary>
        /// Returns the string representation of the object.
        /// </summary>
        public override string ToString()
        {
            return ToString(null, null);
        }

        /// <summary>
        /// Returns the string representation of the object.
        /// </summary>
        /// <exception cref="FormatException"></exception>
        public string ToString(string format, IFormatProvider formatProvider)
        {
            if (format == null)
            {
                if (Instance != null && Instance.SymbolicId != null)
                {
                    return string.Format(formatProvider, "{0}={1}", RelativePath, Instance.SymbolicId.Name);
                }

                return RelativePath;
            }

            throw new FormatException(CoreUtils.Format("Invalid format string: '{0}'.", format));
        }
    }

    /// <summary>
    /// Reference between hierarchy nodes
    /// </summary>
    public class HierarchyReference : IFormattable
    {
        /// <summary>
        /// Source path
        /// </summary>
        public string SourcePath { get; set; }

        /// <summary>
        /// reference type
        /// </summary>
        public XmlQualifiedName ReferenceType { get; set; }

        /// <summary>
        /// Is inverse
        /// </summary>
        public bool IsInverse { get; set; }

        /// <summary>
        /// Target path
        /// </summary>
        public string TargetPath { get; set; }

        /// <summary>
        /// Target id
        /// </summary>
        public XmlQualifiedName TargetId { get; set; }

        /// <summary>
        /// Defined on type
        /// </summary>
        public bool DefinedOnType { get; set; }

        /// <summary>
        /// Returns the string representation of the object.
        /// </summary>
        public override string ToString()
        {
            return ToString(null, null);
        }

        /// <summary>
        /// Returns the string representation of the object.
        /// </summary>
        /// <exception cref="FormatException"></exception>
        public string ToString(string format, IFormatProvider formatProvider)
        {
            if (format == null)
            {
                if (TargetId != null)
                {
                    return string.Format(formatProvider, "{0} => {1}", SourcePath, TargetId.Name);
                }

                return string.Format(formatProvider, "{0} => {1}", SourcePath, TargetPath);
            }

            throw new FormatException(CoreUtils.Format("Invalid format string: '{0}'.", format));
        }
    }

    /// <summary>
    /// Hierarchy information for a type or instance.
    /// </summary>
    public class Hierarchy
    {
        /// <summary>
        /// Type
        /// </summary>
        public TypeDesign Type { get; set; }

        /// <summary>
        /// Nodes
        /// </summary>
        public Dictionary<string, HierarchyNode> Nodes { get; } = [];

        /// <summary>
        /// Node list
        /// </summary>
        public List<HierarchyNode> NodeList { get; } = [];

        /// <summary>
        /// References
        /// </summary>
        public List<HierarchyReference> References { get; set; } = [];
    }

    /// <summary>
    /// A class that stores the model design for a Node.
    /// </summary>
    public partial class NodeDesign : IFormattable
    {
        /// <summary>
        /// Parent node
        /// </summary>
        [XmlIgnore]
        public NodeDesign Parent { get; set; }

        /// <summary>
        /// Has children
        /// </summary>
        [XmlIgnore]
        public bool HasChildren { get; set; }

        /// <summary>
        /// Has references
        /// </summary>
        [XmlIgnore]
        public bool HasReferences { get; set; }

        /// <summary>
        /// State
        /// </summary>
        [XmlIgnore]
#pragma warning disable CA2235 // Mark all non-serializable fields
        public NodeState State { get; set; }
#pragma warning restore CA2235 // Mark all non-serializable fields

        /// <summary>
        /// Instance state
        /// </summary>
        [XmlIgnore]
#pragma warning disable CA2235 // Mark all non-serializable fields
        public NodeState InstanceState { get; set; }
#pragma warning restore CA2235 // Mark all non-serializable fields

        /// <summary>
        /// Hierarchy
        /// </summary>
        [XmlIgnore]
#pragma warning disable CA2235 // Mark all non-serializable fields
        public Hierarchy Hierarchy { get; set; }
#pragma warning restore CA2235 // Mark all non-serializable fields

        /// <summary>
        /// Handle
        /// </summary>
        [XmlIgnore]
        public string Handle { get; set; }

        /// <summary>
        /// Returns the string representation of the object.
        /// </summary>
        public override string ToString()
        {
            return ToString(null, null);
        }

        /// <summary>
        /// Returns the string representation of the object.
        /// </summary>
        /// <exception cref="FormatException"></exception>
        public string ToString(string format, IFormatProvider formatProvider)
        {
            if (format == null)
            {
                if (SymbolicName != null)
                {
                    return string.Format(formatProvider, "{0}", SymbolicName.Name);
                }

                return string.Format(formatProvider, "{0}", GetType().Name);
            }

            throw new FormatException(CoreUtils.Format("Invalid format string: '{0}'.", format));
        }

        /// <summary>
        /// Create symbol
        /// </summary>
        public static string CreateSymbolicId(XmlQualifiedName parentId, string childName)
        {
            if (parentId == null)
            {
                return childName;
            }

            return CreateSymbolicId(parentId.Name, childName);
        }

        /// <summary>
        /// Create symbol
        /// </summary>
        public static string CreateSymbolicId(string parentId, string childName)
        {
            if (string.IsNullOrEmpty(childName))
            {
                return parentId;
            }

            if (string.IsNullOrEmpty(parentId))
            {
                return childName;
            }

            return CoreUtils.Format("{0}{1}{2}", parentId, PathChar, childName);
        }

        /// <summary>
        /// Path character to use when constructing symbolic ids.
        /// </summary>
        public const char PathChar = '_';
    }

    /// <summary>
    /// A class that stores the model design for a Variable.
    /// </summary>
    public partial class VariableDesign
    {
        /// <summary>
        /// Decoded value
        /// </summary>
        [XmlIgnore]
        public object DecodedValue { get; set; }

        /// <summary>
        /// Data type node
        /// </summary>
        [XmlIgnore]
        public DataTypeDesign DataTypeNode { get; set; }
    }

    /// <summary>
    /// A class that stores the model design for a VariableType.
    /// </summary>
    public partial class VariableTypeDesign
    {
        /// <summary>
        /// Decoded value
        /// </summary>
        [XmlIgnore]
        public object DecodedValue { get; set; }

        /// <summary>
        /// Data type node
        /// </summary>
        [XmlIgnore]
        public DataTypeDesign DataTypeNode { get; set; }
    }

    /// <summary>
    /// A class that stores the model design for a Method.
    /// </summary>
    public partial class MethodDesign
    {
        /// <summary>
        /// Has arguments
        /// </summary>
        [XmlIgnore]
        public bool HasArguments { get; set; }

        /// <summary>
        /// Method type node
        /// </summary>
        [XmlIgnore]
        public MethodDesign MethodType { get; set; }

        /// <summary>
        /// Method declaration node
        /// </summary>
        [XmlIgnore]
        public MethodDesign MethodDeclarationNode { get; set; }
    }

    /// <summary>
    /// A class that stores the model design for a Type.
    /// </summary>
    public partial class TypeDesign
    {
        /// <summary>
        /// Base type node
        /// </summary>
        [XmlIgnore]
        public TypeDesign BaseTypeNode { get; set; }

        /// <summary>
        /// Deep copy the type design.
        /// </summary>
        /// <returns></returns>
        public TypeDesign Copy()
        {
            return (TypeDesign)MemberwiseClone();
        }
    }

    /// <summary>
    /// A class that stores the model design for a Type.
    /// </summary>
    public partial class InstanceDesign
    {
        /// <summary>
        /// Type definition node
        /// </summary>
        [XmlIgnore]
        public TypeDesign TypeDefinitionNode { get; set; }

        /// <summary>
        /// Instance declaration node
        /// </summary>
        [XmlIgnore]
        public InstanceDesign InstanceDeclarationNode { get; set; }

        /// <summary>
        /// Overidden node
        /// </summary>
        [XmlIgnore]
        public InstanceDesign OveriddenNode { get; set; }

        /// <summary>
        /// Identifier required
        /// </summary>
        [XmlIgnore]
        public bool IdentifierRequired { get; set; }

        /// <summary>
        /// Deep copy the instance design.
        /// </summary>
        public InstanceDesign Copy()
        {
            return (InstanceDesign)MemberwiseClone();
        }
    }

    /// <summary>
    /// A class that stores a reference between nodes.
    /// </summary>
    public partial class Reference
    {
        /// <summary>
        /// Source node
        /// </summary>
        [XmlIgnore]
        public NodeDesign SourceNode { get; set; }

        /// <summary>
        /// Source relative path
        /// </summary>
        [XmlIgnore]
#pragma warning disable CA2235 // Mark all non-serializable fields
        public RelativePath SourceRelativePath { get; set; }
#pragma warning restore CA2235 // Mark all non-serializable fields

        /// <summary>
        /// Target node
        /// </summary>
        [XmlIgnore]
        public NodeDesign TargetNode { get; set; }

        /// <summary>
        /// Target relative path
        /// </summary>
        [XmlIgnore]
#pragma warning disable CA2235 // Mark all non-serializable fields
        public RelativePath TargetRelativePath { get; set; }
#pragma warning restore CA2235 // Mark all non-serializable fields
    }

    /// <summary>
    /// A class that stores a parameter for a node.
    /// </summary>
    public partial class Parameter
    {
        /// <summary>
        /// Parent node
        /// </summary>
        [XmlIgnore]
        public NodeDesign Parent { get; set; }

        /// <summary>
        /// Data type node
        /// </summary>
        [XmlIgnore]
        public DataTypeDesign DataTypeNode { get; set; }

        /// <summary>
        /// Identifier is in name
        /// </summary>
        [XmlIgnore]
        public bool IdentifierInName { get; set; }

        /// <summary>
        /// Is inherited
        /// </summary>
        [XmlIgnore]
        public bool IsInherited { get; set; }
    }

    /// <summary>
    /// The set of basic data types
    /// </summary>
    public enum BasicDataType
    {
        /// <summary>
        /// Boolean data type
        /// </summary>
        Boolean,

        /// <summary>
        /// Signed byte data type
        /// </summary>
        SByte,

        /// <summary>
        /// Unsigned byte data type
        /// </summary>
        Byte,

        /// <summary>
        /// 16-bit signed integer data type
        /// </summary>
        Int16,

        /// <summary>
        /// 16-bit unsigned integer data type
        /// </summary>
        UInt16,

        /// <summary>
        /// 32-bit signed integer data type
        /// </summary>
        Int32,

        /// <summary>
        /// 32-bit unsigned integer data type
        /// </summary>
        UInt32,

        /// <summary>
        /// 64-bit signed integer data type
        /// </summary>
        Int64,

        /// <summary>
        /// 64-bit unsigned integer data type
        /// </summary>
        UInt64,

        /// <summary>
        /// Single-precision floating point data type
        /// </summary>
        Float,

        /// <summary>
        /// Double-precision floating point data type
        /// </summary>
        Double,

        /// <summary>
        /// String data type
        /// </summary>
        String,

        /// <summary>
        /// DateTime data type
        /// </summary>
        DateTime,

        /// <summary>
        /// Globally unique identifier data type
        /// </summary>
        Guid,

        /// <summary>
        /// Byte string data type
        /// </summary>
        ByteString,

        /// <summary>
        /// XML element data type
        /// </summary>
        XmlElement,

        /// <summary>
        /// Node identifier data type
        /// </summary>
        NodeId,

        /// <summary>
        /// Expanded node identifier data type
        /// </summary>
        ExpandedNodeId,

        /// <summary>
        /// Status code data type
        /// </summary>
        StatusCode,

        /// <summary>
        /// Diagnostic information data type
        /// </summary>
        DiagnosticInfo,

        /// <summary>
        /// Qualified name data type
        /// </summary>
        QualifiedName,

        /// <summary>
        /// Localized text data type
        /// </summary>
        LocalizedText,

        /// <summary>
        /// Data value data type
        /// </summary>
        DataValue,

        /// <summary>
        /// Numeric data type
        /// </summary>
        Number,

        /// <summary>
        /// Integer data type
        /// </summary>
        Integer,

        /// <summary>
        /// Unsigned integer data type
        /// </summary>
        UInteger,

        /// <summary>
        /// Enumeration data type
        /// </summary>
        Enumeration,

        /// <summary>
        /// Structure data type
        /// </summary>
        Structure,

        /// <summary>
        /// Base data type
        /// </summary>
        BaseDataType,

        /// <summary>
        /// User-defined data type
        /// </summary>
        UserDefined
    }

    /// <summary>
    /// A class that stores the model design for a DataType.
    /// </summary>
    public partial class DataTypeDesign
    {
        /// <summary>
        /// Has encodings
        /// </summary>
        [XmlIgnore]
        public bool HasEncodings { get; set; }

        /// <summary>
        /// Has fields
        /// </summary>
        [XmlIgnore]
        public bool HasFields { get; set; }

        /// <summary>
        /// Is structure
        /// </summary>
        [XmlIgnore]
        public bool IsStructure { get; set; }

        /// <summary>
        /// Is enumeration
        /// </summary>
        [XmlIgnore]
        public bool IsEnumeration { get; set; }

        /// <summary>
        /// Built in data type
        /// </summary>
        [XmlIgnore]
        public BasicDataType BasicDataType { get; set; }
    }
}
