apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pump-device-integration-server-pki
  labels:
    app.kubernetes.io/name: pump-device-integration-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pump-device-integration-server
  labels:
    app.kubernetes.io/name: pump-device-integration-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pump-device-integration-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pump-device-integration-server
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1654
        fsGroup: 1654
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: app
          image: ghcr.io/opcfoundation/pumpdeviceintegrationserver:latest
          env:
            - name: DOTNET_DiagnosticPorts
              value: /diag/dotnet-diagnostic.sock,connect,nosuspend
            - name: pkiRoot
              value: /app/pki
          ports:
            - name: opc-tcp
              containerPort: 62542
              protocol: TCP
          volumeMounts:
            - name: diagnostics
              mountPath: /diag
            - name: pki
              mountPath: /app/pki
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - name: dotnet-diag
          image: ghcr.io/koepalex/dotnet-k8s-debug-containers/diag:latest
          stdin: true
          tty: true
          volumeMounts:
            - name: diagnostics
              mountPath: /diag
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: diagnostics
          emptyDir: {}
        - name: pki
          persistentVolumeClaim:
            claimName: pump-device-integration-server-pki
---
apiVersion: v1
kind: Service
metadata:
  name: pump-device-integration-server
  labels:
    app.kubernetes.io/name: pump-device-integration-server
spec:
  selector:
    app.kubernetes.io/name: pump-device-integration-server
  ports:
    - name: opc-tcp
      port: 62542
      targetPort: opc-tcp
      protocol: TCP
