//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opc.Ua.Gds
{
    using System.Data.Entity;

    public partial class gdsdbEntities
    {
        public DbSet<ApplicationName> ApplicationNames { get; set; }
        public DbSet<ServerEndpoint> ServerEndpoints { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<CertificateStore> CertificateStores { get; set; }
        public DbSet<CertificateRequest> CertificateRequests { get; set; }
    }
}
