#
# Build and test all on all platforms
#
jobs:
- job: buildprep
  displayName: Prepare Build Jobs
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    skipComponentGovernanceDetection: true
  steps:
  - task: PowerShell@2
    name: buildmatrix
    displayName: Prepare Solutions
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/get-matrix.ps1
      arguments: -FileName "NetCore*.csproj"
- job: buildall
  displayName: Building
  dependsOn: buildprep
  strategy:
    matrix: $[dependencies.buildprep.outputs['buildmatrix.jobMatrix'] ]
  pool:
    vmImage: $(poolImage)
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: sdk
      version: 2.1.x
      includePreviewVersions: false
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Release Build
    inputs:
      command: build
      projects: '$(file)'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: Debug Build
    inputs:
      command: build
      projects: '$(file)'
      arguments: '--configuration Debug'
- job: testprep
  displayName: Prepare Test Jobs
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    skipComponentGovernanceDetection: true
  steps:
  - task: PowerShell@2
    name: testmatrix
    displayName: Prepare Tests
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/get-matrix.ps1
      arguments: -FileName azure-pipelines.yml
- job: testall
  displayName: Run Tests for
  dependsOn: testprep
  strategy:
    matrix: $[dependencies.testprep.outputs['testmatrix.jobMatrix'] ]
  variables:
    skipComponentGovernanceDetection: true
  pool:
    vmImage: $(poolImage)
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: sdk
      version: 2.1.x
      includePreviewVersions: false
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Test Release
    timeoutInMinutes: 20
    inputs:
      command: test
      projects: '**/*.Tests.csproj'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: Test Debug
    timeoutInMinutes: 20
    inputs:
      command: test
      projects: '**/*.Tests.csproj'
      arguments: '--configuration Debug'
  - task: DotNetCoreCLI@2
    displayName: Test GDS Release
    timeoutInMinutes: 20
    inputs:
      command: test
      projects: '**/GlobalDiscoveryClientTest.csproj'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: Test GDS Debug
    timeoutInMinutes: 20
    inputs:
      command: test
      projects: '**/GlobalDiscoveryClientTest.csproj'
      arguments: '--configuration Debug'
