#
# Build preview packages for internal feed
#
parameters:
  upload: false
jobs:
- job: buildnuget
  displayName: Build Nuget Preview Packages
  pool:
    vmImage: 'windows-2019'
  variables:
  - group: codesign
  - name: msbuildversion
    value: '/p:Version=$(NUGETVERSION) /p:AssemblyVersion=$(NUGETVERSION) /p:FileVersion=$(NUGETVERSION)'
  - name: msbuildsign
    value: '/p:AssemblyOriginatorKeyFile=$(strongnamefile.secureFilePath) /p:SignAssembly=true'
  - name: nugetpreviewversion
    value: '$(NUGETVERSION)-$(Build.BuildNumber)-$(Build.SourceBranchName)-preview'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --global azuresigntool'
    displayName: Install AzureSignTool
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --global NuGetKeyVaultSignTool'
    displayName: Install NuGetKeyVaultSignTool
  - task: PowerShell@2
    displayName: Sign Nuget
    inputs:
      targetType: 'inline'
      script: |
        .\NuGetKeyVaultSignTool sign "$(Build.ArtifactStagingDirectory)/**/*.nupkg" --file-digest sha256 --timestamp-rfc3161 http://timestamp.digicert.com --timestamp-digest sha256 --azure-key-vault-url "$(SigningVaultURL)" --azure-key-vault-client-id "$(SigningClientId)" --azure-key-vault-tenant-id "$(SigningTenantId)" --azure-key-vault-client-secret "$(SigningClientSecret)" --azure-key-vault-certificate "$(SigningCertName)" 
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=5.4.x'
  - task: DotNetCoreCLI@2
    displayName: Release Restore
    inputs:
      command: restore
      projects: '**/Opc.Ua.*.csproj'
      arguments: '--configuration Release'
  - task: DownloadSecureFile@1
    name: strongnamefile
    displayName: 'Download Strong Name Key'
    inputs:
      secureFile: 'OPCFoundation.NetStandard.Key.snk'
  - task: DotNetCoreCLI@2
    displayName: Release Build
    inputs:
      command: build
      projects: '**/Opc.Ua.*.csproj'
      arguments: '--no-restore --configuration Release ${{ variables.msbuildversion }} ${{ variables.msbuildsign }}'
  - task: DotNetCoreCLI@2
    displayName: Debug Build
    inputs:
      command: build
      projects: '**/Opc.Ua.*.csproj'
      arguments: '--no-restore --configuration Debug ${{ variables.msbuildversion }} ${{ variables.msbuildsign }}'
  - task: CmdLine@2
    displayName: 'Sign Assemblies'
    inputs:
      script: |
        azuresigntool sign -du "$(SigningURL)" -kvu "$(SigningVaultURL)" -kvi "$(SigningClientId)" -tr http://timestamp.digicert.com -td sha384 -kvs "$(SigningClientSecret)" -kvc "$(SigningCertName)" -v -ifl .azurepipelines/signlist.txt
  - task: NuGetCommand@2
    displayName: Pack Nuget Preview
    continueOnError: true
    inputs:
      command: 'pack'
      packagesToPack: '**/*.nuspec'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'nugetpreviewversion'
  - script: |
      NuGetKeyVaultSignTool sign "$(Build.ArtifactStagingDirectory)/**/*.nupkg" --file-digest sha256 --timestamp-rfc3161 http://timestamp.digicert.com --timestamp-digest sha256 --azure-key-vault-url "$(SigningVaultURL)" --azure-key-vault-client-id "$(SigningClientId)" --azure-key-vault-tenant-id "$(SigningTenantId)" --azure-key-vault-client-secret "$(SigningClientSecret)" --azure-key-vault-certificate "$(SigningCertName)" 
    displayName: Sign Nuget
  - task: NuGetCommand@2
    displayName: Upload Nuget Preview
    condition: ${{ variables.upload }}
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(VSTSFEED)'
      allowPackageConflicts: true