#
# Build preview packages for internal feed
#
parameters:
- name: upload
- name: config
  type: string
  default: Release
  values: 
  - Debug
  - Release

jobs:
- job: nuget${{parameters.config}}
  displayName: Pack Nugets ${{parameters.config}}
  pool:
    vmImage: 'windows-2019'
  variables:
  - group: codesign
  - name: msbuildversion
    value: '/p:Version=$(NBGV_Version) /p:AssemblyVersion=$(NBGV_SimpleVersion) /p:FileVersion=$(NBGV_AssemblyFileVersion)'
  - name: msbuildsign
    value: '/p:AssemblyOriginatorKeyFile=$(strongnamefile.secureFilePath) /p:SignAssembly=true'
  - name: nugetpreviewversion
    value: '$(NBGV_NuGetPackageVersion)'
  - name: signinglist
    value: '.azurepipelines/signlist${{parameters.config}}.txt'
  steps:
  - task: DownloadSecureFile@1
    name: strongnamefile
    displayName: 'Download Strong Name Key'
    inputs:
      secureFile: 'OPCFoundation.NetStandard.Key.snk'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --tool-path . azuresigntool'
    displayName: Install AzureSignTool
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'install --version 3.0.45 --tool-path . NuGetKeyVaultSignTool'
    displayName: Install NuGetKeyVaultSignTool
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=5.4.x'
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/set-version.ps1
  - task: DotNetCoreCLI@2
    displayName: Release Restore
    inputs:
      command: restore
      projects: 'UA Core Library.sln'
      arguments: '--configuration ${{parameters.config}}'
  - task: DotNetCoreCLI@2
    displayName: Build ${{parameters.config}}
    inputs:
      command: build
      projects: 'UA Core Library.sln'
      arguments: '--no-restore --configuration ${{parameters.config}} ${{ variables.msbuildversion }} ${{ variables.msbuildsign }}'
  - task: CmdLine@2
    displayName: 'Sign Assemblies'
    condition: ne( variables['SigningClientSecret'], '')
    inputs:
      script: |
        azuresigntool sign -du "$(SigningURL)" -kvu "$(SigningVaultURL)" -kvi "$(SigningClientId)" -tr http://timestamp.digicert.com -td sha384 -kvs "$(SigningClientSecret)" -kvc "$(SigningCertName)" -v -ifl ${{ variables.signinglist }}
  - task: DotNetCoreCLI@2
    displayName: Pack Nuget ${{parameters.config}}
    inputs:
      command: pack
      packagesToPack:  'UA Core Library.sln'
      configuration: ${{parameters.config}}
      configurationToPack: ${{parameters.config}}
      nobuild: true
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'nugetpreviewversion'
      includeSymbols: true
  - task: NuGetCommand@2
    displayName: Pack Nuget Legacy
    condition: and(eq( '${{parameters.config}}', 'Release'), succeeded())
    continueOnError: true
    inputs:
      command: 'pack'
      packagesToPack: '**/Opc.Ua.*.nuspec'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'nugetpreviewversion'
      includeSymbols: true
  - task: CmdLine@2
    displayName: 'List of nuget packages to sign'
    inputs:
      script: |
        dir /b /s $(Build.ArtifactStagingDirectory)\OPCFoundation.*.nupkg > .\nupkglist.txt
        type .\nupkglist.txt
  - task: CmdLine@2
    displayName: Sign Nuget packages
    condition: and(ne( variables['SigningClientSecret'], ''), succeeded())
    continueOnError: true
    inputs:
      script: |
        NuGetKeyVaultSignTool sign $(Build.ArtifactStagingDirectory)/**/OPCFoundation.*.nupkg --file-digest sha256 --timestamp-rfc3161 http://timestamp.digicert.com --timestamp-digest sha256 --azure-key-vault-url "$(SigningVaultURL)" --azure-key-vault-client-id "$(SigningClientId)" --azure-key-vault-tenant-id "$(SigningTenantId)" --azure-key-vault-client-secret "$(SigningClientSecret)" --azure-key-vault-certificate "$(SigningCertName)" 
  - task: NuGetCommand@2
    displayName: Upload Nuget Preview
    condition: false #${{ variables.upload }}
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/OPCFoundation.*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(VSTSFEED)'
      allowPackageConflicts: true