#
# Build and test all on all platforms
#
jobs:
- job: prepsln
  displayName: Prepare Solution Build Jobs
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: PowerShell@2
    name: slnmatrix
    displayName: Prepare Solutions
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/get-matrix.ps1
      arguments: -FileName "*.sln" -AgentTable @{ windows = "vs2017-win2016" }
- job: buildallsln
  displayName: Build
  dependsOn: prepsln
  strategy:
    matrix: $[dependencies.prepsln.outputs['slnmatrix.jobMatrix'] ]
  pool:
    vmImage: $(poolImage)
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: DotNetCoreCLI@2
    displayName: Release Restore
    inputs:
      command: restore
      projects: '$(file)'
      arguments: '--configuration Release'
  - task: MSBuild@1
    displayName: MS Build Release
    inputs:
      solution: '$(file)' 
      configuration: 'Release'
  - task: DotNetCoreCLI@2
    displayName: Debug Restore
    inputs:
      command: restore
      projects: '$(file)'
      arguments: '--configuration Debug'
  - task: MSBuild@1
    displayName: MS Build Release
    inputs:
      solution: '$(file)' 
      configuration: 'Debug'
