#
# Build and test all on all platforms
#
jobs:
- job: prepsln
  displayName: Prepare Solution Build Jobs
  pool:
    vmImage: 'windows-2019'
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: PowerShell@2
    name: slnmatrix
    displayName: Prepare Solution
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/get-matrix.ps1
      arguments: -FileName "*.sln" -AgentTable @{ windows = "windows-2019" }
- job: buildallsln
  displayName: Build Solutions
  dependsOn: prepsln
  strategy:
    matrix: $[dependencies.prepsln.outputs['slnmatrix.jobMatrix'] ]
  pool:
    vmImage: $(poolImage)
  steps:
#  - task: UseDotNet@2
#    displayName: 'Install .NET Core SDK'
#    inputs:
#      packageType: sdk
#      version: 2.1.x
#      includePreviewVersions: false
#      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Release Restore
    inputs:
      command: restore
      projects: '$(file)'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: Release Build
    inputs:
      command: build
      projects: '$(file)'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: Debug Restore
    inputs:
      command: restore
      projects: '$(file)'
      arguments: '--configuration Debug'
  - task: DotNetCoreCLI@2
    displayName: Debug Build
    inputs:
      command: build
      projects: '$(file)'
      arguments: '--configuration Debug'
