#
# Build and test all on all platforms
#
jobs:
- job: buildprepsln
  displayName: Prepare Solution Build Jobs
  pool:
    vmImage: 'windows-2019'
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: PowerShell@2
    name: solutionmatrix
    displayName: Prepare Solution
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/get-matrix.ps1
      arguments: -FileName "UA *.sln" -Agent "windows"
- job: buildallsln
  displayName: Build Solutions
  dependsOn: buildprepsln
  strategy:
    matrix: $[dependencies.buildprep.outputs['solutionmatrix.jobMatrix'] ]
  pool:
    vmImage: 'windows-2019'
  steps:
#  - task: UseDotNet@2
#    displayName: 'Install .NET Core SDK'
#    inputs:
#      packageType: sdk
#      version: 2.1.x
#      includePreviewVersions: false
#      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Release Build
    inputs:
      command: build
      projects: '$(file)'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: Debug Build
    inputs:
      command: build
      projects: '$(file)'
      arguments: '--configuration Debug'
