#
# Build all solutions on windows
#
parameters:
  poolImage: 'windows-2022'
  jobnamesuffix: ''

jobs:
- job: buildallsln${{ parameters.jobnamesuffix }}
  displayName: Build Solutions ${{ parameters.jobnamesuffix }}
  pool:
    vmImage: ${{ parameters.poolImage }}
  steps:
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=5.8.x'
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/set-version.ps1
  - task: NuGetCommand@2
    displayName: Restore Release
    inputs:
      command: restore
      restoreSolution: '**/*.sln'
      configuration: 'Release'
  - task: MSBuild@1
    displayName: MS Build Release
    inputs:
      solution: '**/*.sln' 
      configuration: 'Release'
      platform: 'Any CPU'
      msbuildArguments: 
  - task: NuGetCommand@2
    displayName: Restore Debug
    inputs:
      command: restore
      restoreSolution: '**/*.sln'
      configuration: 'Debug'
  - task: MSBuild@1
    displayName: MS Build Debug
    inputs:
      solution: '**/*.sln'
      configuration: 'Debug'
      platform: 'Any CPU'
      msbuildArguments: 
