#
# Build and test all on all platforms
#
jobs:
- job: prepsln
  displayName: Prepare Solution Build Jobs
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: PowerShell@2
    name: slnmatrix
    displayName: Prepare Solutions
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/get-matrix.ps1
      arguments: -FileName "*.sln" -AgentTable @{ windows = "vs2017-win2016" }
- job: buildallsln
  displayName: Build
  dependsOn: prepsln
  strategy:
#    matrix: $[dependencies.prepsln.outputs['slnmatrix.jobMatrix'] ]
    matrix: 
      UACoreLibrary: 
        file: 'UA Core Library.sln'
        poolImage: 'vs2017-win2016'
      UAGlobalDiscoveryServer: 
        file: 'UA Global Discovery Server.sln'
        poolImage: 'vs2017-win2016'
      UACoreLibrary-NoHttps: 
        file: 'UA Core Library.sln'
        poolImage: 'win2019'
        args: '/p:NoHttps=true'

  pool:
    vmImage: $(poolImage)
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: DotNetCoreCLI@2
    displayName: Release Restore
    inputs:
      command: restore
      projects: '$(file)'
      arguments: '--configuration Release'
  - task: MSBuild@1
    displayName: MS Build Release
    inputs:
      solution: '$(file)' 
      configuration: 'Release'
      platform: 'Any CPU'
      msbuildArguments:'$(args)'
  - task: DotNetCoreCLI@2
    displayName: Debug Restore
    inputs:
      command: restore
      projects: '$(file)'
      arguments: '--configuration Debug'
  - task: MSBuild@1
    displayName: MS Build Debug
    inputs:
      solution: '$(file)' 
      configuration: 'Debug'
      platform: 'Any CPU'
      msbuildArguments:'$(args)'
- job: buildNoHttps
  dependsOn: prepsln
  displayName: Build NoHttps
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: 'UA Core Library.sln'
      arguments: '--configuration Release'
  - task: MSBuild@1
    displayName: MS Build Release No Https
    inputs:
      solution: 'UA Core Library.sln'
      configuration: 'Release'
      msbuildArguments: '/p:NoHttps=true'
