#
# Build all solutions on windows
#
parameters:
  poolImage: 'windows-2025'
  jobnamesuffix: ''

jobs:
- job: buildallsln${{ parameters.jobnamesuffix }}
  displayName: Build Solutions ${{ parameters.jobnamesuffix }}
  pool:
    vmImage: ${{ parameters.poolImage }}
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 10.0'
    inputs:
      packageType: 'sdk'
      version: '10.0.x'
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=7.0.x'
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/set-version.ps1
  - task: NuGetCommand@2
    displayName: Restore Release
    inputs:
      command: restore
      restoreSolution: '**/*.slnx'
      configuration: 'Release'
  - task: MSBuild@1
    displayName: MS Build Release
    inputs:
      solution: '**/*.slnx'
      msbuildVersion: 'latest'
      configuration: 'Release'
      platform: 'Any CPU'
      msbuildArguments:
  - task: NuGetCommand@2
    displayName: Restore Debug
    inputs:
      command: restore
      restoreSolution: '**/*.slnx'
      configuration: 'Debug'
  - task: MSBuild@1
    displayName: MS Build Debug
    inputs:
      solution: '**/*.slnx'
      msbuildVersion: 'latest'
      configuration: 'Debug'
      platform: 'Any CPU'
      msbuildArguments:
