#
# Build all solutions on Windows
#
jobs:
- job: buildwinsln
  displayName: Build Windows Solutions
  pool:
    vmImage: 'windows-2019'
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: MSBuild@1
      inputs:
      solution: '**/*.sln' 
      #msbuildLocationMethod: 'version' # Optional. Options: version, location
      #msbuildVersion: 'latest' # Optional. Options: latest, 16.0, 15.0, 14.0, 12.0, 4.0
      #msbuildArchitecture: 'x86' # Optional. Options: x86, x64
      #msbuildLocation: # Optional
      #platform: # Optional
      configuration: "Release"
      #msbuildArguments: # Optional
      clean: false # Optional
      #maximumCpuCount: false # Optional
      #restoreNugetPackages: false # Optional
      #logProjectEvents: false # Optional
      #createLogFile: false # Optional
      #logFileVerbosity: 'normal' # Optional. Options: quiet, minimal, normal, detailed, diagnostic
