#
# Test all .Net Core projects on all platforms
#
parameters:
  configuration: 'Release'
  framework: net8.0
  agents: '@{}'
  jobnamesuffix: ''
  customtestarget: ''
jobs:
- job: testprep${{ parameters.jobnamesuffix }}
  displayName: Prepare Test Jobs ${{ parameters.configuration }} (${{ parameters.framework }})
  pool:
    vmImage: 'windows-2025'
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: PowerShell@2
    name: testmatrix
    displayName: Prepare Tests
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/get-matrix.ps1
      arguments: -FileName *.Tests.csproj -AgentTable ${{ parameters.agents }}
- job: testall${{ parameters.jobnamesuffix }}
  displayName: Tests (${{ parameters.framework }})
  dependsOn: testprep${{ parameters.jobnamesuffix }}
  timeoutInMinutes: 120
  strategy:
    matrix: $[dependencies.testprep${{ parameters.jobnamesuffix }}.outputs['testmatrix.jobMatrix'] ]
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    CustomTestTarget: ${{ parameters.customtestarget }}
    ${{ if eq( parameters.customtestarget, '' ) }}:
      DotCliCommandline: '--framework ${{ parameters.framework }}'
    ${{ else }}:
      DotCliCommandline: '/p:CustomTestTarget=${{ parameters.customtestarget }}'
  pool:
    vmImage: $(poolImage)
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 8.0'
    condition: eq('${{parameters.framework}}', 'net8.0')
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
  - task: UseDotNet@2
    displayName: 'Install .NET 9.0'
    condition: eq('${{parameters.framework}}', 'net9.0')
    inputs:
      packageType: 'sdk'
      version: '9.0.x'
  - task: UseDotNet@2
    displayName: 'Install .NET 10.0'
    inputs:
      packageType: 'sdk'
      version: '10.0.x'
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=7.0.x'
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/set-version.ps1
  - task: DownloadSecureFile@1
    name: fuzzingartifacts
    displayName: 'Download Fuzzing artifacts'
    inputs:
      secureFile: 'FuzzingArtifacts.zip'
  - task: ExtractFiles@1
    displayName: 'Extract Fuzzing artifacts'
    condition: ne(variables['fuzzingartifacts.secureFilePath'], '')
    inputs:
      archiveFilePatterns: '$(Agent.TempDirectory)/FuzzingArtifacts.zip'
      destinationFolder: ./Fuzzing/Encoders/Fuzz.Tests
      cleanDestinationFolder: false
      overwriteExistingFiles: true
    continueOnError: true
  - task: DotNetCoreCLI@2
    displayName: Restore ${{ parameters.configuration }}
    inputs:
      command: restore
      projects: $(file)
      arguments: '${{ variables.DotCliCommandline }} --configuration ${{ parameters.configuration }}'
  - task: DotNetCoreCLI@2
    displayName: Test ${{ parameters.configuration }}
    timeoutInMinutes: 45
    inputs:
      command: test
      projects: $(file)
      arguments: '--no-restore ${{ variables.DotCliCommandline }} --configuration ${{ parameters.configuration }}'
