#
# Test all .Net Core projects on all platforms
#
parameters:
  configuration: 'Release'
  framework: netcoreapp2.1
  agents: '@{}'
  jobnamesuffix: ''
jobs:
- job: testprep${{ parameters.jobnamesuffix }}
  displayName: Prepare Test Jobs ${{ parameters.configuration }} (${{ parameters.framework }})
  pool:
    vmImage: 'windows-2019'
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  steps:
  - task: PowerShell@2
    name: testmatrix
    displayName: Prepare Tests
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/get-matrix.ps1
      arguments: -FileName azure-pipelines.yml -AgentTable ${{ parameters.agents }}
- job: testall${{ parameters.jobnamesuffix }}
  displayName: Tests (${{ parameters.framework }})
  dependsOn: testprep${{ parameters.jobnamesuffix }}
  strategy:
    matrix: $[dependencies.testprep${{ parameters.jobnamesuffix }}.outputs['testmatrix.jobMatrix'] ]
  variables:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  pool:
    vmImage: $(poolImage)
  steps:
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=5.8.x'
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./.azurepipelines/set-version.ps1
  - task: DotNetCoreCLI@2
    displayName: Restore ${{ parameters.configuration }}
    inputs:
      command: restore
      projects: '**/*.Tests.csproj'
      arguments: '--framework ${{ parameters.framework }} --configuration ${{ parameters.configuration }}'
  - task: DotNetCoreCLI@2
    displayName: Test ${{ parameters.configuration }}
    timeoutInMinutes: 20
    inputs:
      command: test
      projects: '**/*.Tests.csproj'
      arguments: '--no-restore --framework ${{ parameters.framework }} --configuration ${{ parameters.configuration }}'
