#
# Pack nugets for consumption
#
parameters:
  sign: 'False'
jobs:
- job: nuget
  displayName: Pack Nugets
  pool:
    name: Hosted Windows 2019 with VS2017
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK for signing'
    inputs:
      packageType: sdk
      version: 2.0.x
      includePreviewVersions: false
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK for building'
    inputs:
      packageType: sdk
      version: 2.1.x
      includePreviewVersions: false
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: PowerShell@2
    displayName: Versioning
    inputs:
      targetType: filePath
      filePath: ./tools/scripts/set-version.ps1
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: 'UA Core Library.sln'
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: 'UA Core Library.sln'
      arguments: '--configuration Release'
  - task: AntiMalware@3
    displayName: 'Run Virus scan'
    inputs:
      InputType: 'Basic'
      ScanType: 'CustomScan'
      FileDirPath: '$(Build.StagingDirectory)'
      EnableServices: true
      SupportLogOnError: false
      TreatSignatureUpdateFailureAs: 'Warning'
      SignatureFreshness: 'UpToDate'
      TreatStaleSignatureAs: 'Error'
  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packagesToPack: 'UA Core Library.sln'
      configuration: Release
      configurationToPack: Release
      nobuild: true
  - task: ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact'
    inputs:
      path: $(Build.ArtifactStagingDirectory)
      artifact: 'release_nugets_opcua'
