"""Regenerates the referenced pump assets from the P101 master in Plant.usda.

pump.usda and remote-pump.usda are the component assets a ProductionLine
references once per aggregated pump. They must carry the same geometry as
/Plant/Pumps/P101 so every pump in the line renders at full fidelity, but they
have to be self-contained: material paths are rewritten to a local Looks scope.

Run from the repository root:
    python samples/PumpDeviceIntegrationServer/Assets/generate_pump_assets.py
"""

import pathlib
import re

HERE = pathlib.Path(__file__).parent
PLANT = HERE / "Plant.usda"

# The P101 children that make up the machine itself, including the signalling
# equipment. Every configured pump is now composed from this asset and driven by
# its own bindings, so each machine carries its own beacon, status light and
# suction vessel rather than sharing one plant-side set.
WANTED = [
    "Baseplate",
    "Body",
    "Casing",
    "Suction",
    "SuctionVessel",
    "Discharge",
    "PowerEnd",
    "Bearing",
    "Impeller",
    "CouplingGuard",
    "Motor",
    "Beacon",
    "StatusLight",
]

# KSB signal blue (RAL 5005) -> OEM moss green (RAL 6011), so the pump federated
# from the remote server is obvious at a glance.
GREEN = {
    "(0.02, 0.24, 0.60)": "(0.24, 0.36, 0.20)",
    "(0.02, 0.22, 0.55)": "(0.22, 0.33, 0.18)",
    "(0.02, 0.20, 0.50)": "(0.20, 0.30, 0.16)",
}


def block(lines, start):
    """Returns the line range of a brace-delimited prim block starting at `start`."""
    depth = 0
    index = start
    seen = False
    while index < len(lines):
        depth += lines[index].count("{") - lines[index].count("}")
        if "{" in lines[index]:
            seen = True
        if seen and depth == 0:
            return start, index + 1
        index += 1
    raise ValueError(f"unterminated block at line {start}")


def extract(text, name, indent):
    """Extracts the named prim block at the given indent, dedented to column 4."""
    lines = text.splitlines()
    pattern = re.compile(rf'^{" " * indent}def \w+ "{re.escape(name)}"')
    for index, line in enumerate(lines):
        if pattern.match(line):
            first, last = block(lines, index)
            body = lines[first:last]
            trim = indent - 4
            return "\n".join(line[trim:] if line.startswith(" " * trim) else line
                             for line in body)
    raise ValueError(f"prim {name!r} not found at indent {indent}")


def looks(text):
    """Extracts the shared Looks scope and rehomes it under /Pump."""
    scope = extract(text, "Looks", 4)
    return scope.replace("</Plant/Looks/", "</Pump/Looks/")


def rehome(text):
    text = text.replace("</Plant/Looks/", "</Pump/Looks/")
    text = text.replace("</Plant/Pumps/P101/", "</Pump/")
    return text


def build(plant, doc, recolour):
    parts = [looks(plant)]
    parts += [extract(plant, name, 12) for name in WANTED]
    body = rehome("\n\n".join(parts))
    if recolour:
        for blue, green in GREEN.items():
            body = body.replace(blue, green)
    return f'''#usda 1.0
(
    doc = """{doc}"""
    defaultPrim = "Pump"
    metersPerUnit = 1
    upAxis = "Z"
)

def Xform "Pump" (
    kind = "component"
)
{{
{body}
}}
'''


PUMP_DOC = """Reusable single-pump USD asset for the OPC UA - OpenUSD Bindings
    composition demo. The server composes one referenced </Pump> prim per
    configured pump (--pumps N), and a ProductionLine aggregates further pumps
    the same way (spec 5.12, CompositionArc = Reference/Instance). The
    cross-server component references an equivalent OEM asset (remote-pump.usda)
    on another server (5.14).

    Generated by generate_pump_assets.py from the /Plant/Pumps/P101 master in
    Plant.usda, so every composed pump renders at the same fidelity: an EN 733
    size 65-200 end-suction centrifugal pump (Grundfos NK / KSB Etanorm
    proportions) driven by an IEC 160M motor on a 1.80 x 0.46 m baseplate, shaft
    centreline 0.160 m above the baseplate. Do not edit by hand - edit P101 and
    re-run the generator.

    The asset carries its own signalling and instrumentation - beacon, status
    light, pressure and bearing-temperature gauges, suction vessel, cooling fan -
    because each composed pump is driven by its own bindings and has to show its
    own state."""

REMOTE_DOC = """OEM pump asset served by a *different* OPC UA server, referenced
    across the federation boundary by the cross-server <Component> binding
    (spec 5.14). Geometrically identical to pump.usda so the composed line reads
    consistently, but wearing the OEM's own livery - moss green (RAL 6011)
    castings instead of KSB signal blue.

    Generated by generate_pump_assets.py from the /Plant/Pumps/P101 master in
    Plant.usda. Do not edit by hand - edit P101 and re-run the generator."""


def main():
    plant = PLANT.read_text(encoding="utf-8")
    (HERE / "pump.usda").write_text(
        build(plant, PUMP_DOC, recolour=False), encoding="utf-8", newline="\r\n")
    (HERE / "remote-pump.usda").write_text(
        build(plant, REMOTE_DOC, recolour=True), encoding="utf-8", newline="\r\n")
    print("wrote pump.usda and remote-pump.usda")


if __name__ == "__main__":
    main()
