<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Sdk.props" Sdk="Aspire.AppHost.Sdk" Version="13.6.0"
          Condition="'$(CustomTestTarget)' == '' OR '$(CustomTestTarget)' == 'net10.0'" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RestrictForLegacyTfm>true</RestrictForLegacyTfm>
    <IsAspireHost Condition="'$(CustomTestTarget)' == '' OR '$(CustomTestTarget)' == 'net10.0'">true</IsAspireHost>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <RootNamespace>UaLens.AppHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../samples/DI/PumpDeviceIntegrationServer/PumpDeviceIntegrationServer.csproj"
                      AdditionalProperties="CustomTestTarget=net10.0" />
    <ProjectReference Include="../Opc.Ua.Lens/Opc.Ua.Lens.csproj"
                      AdditionalProperties="CustomTestTarget=net10.0;PublishAotEnabled=false" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Aspire.AppHost.Sdk" Version="13.6.0"
          Condition="'$(CustomTestTarget)' == '' OR '$(CustomTestTarget)' == 'net10.0'" />
</Project>
