// <auto-generated>
// Generated by tools/GenerateRegistryNativeCatalog.py. Do not edit; regenerate from the pinned
// specification catalog instead. Provenance (also recorded in tools/registry-native-catalog.json):
//   repository: OPCF-Members/OPC30450-CloudInitiative
//   commit: db011ea4496570311332bedf33d5d78d91d26cc0
//   uncommittedSource: false
//   catalog: 80a33dbaf36ab30cdd8267ab18984e8310e5ab6d83386dad2a25ba3045fdb637
//   Endpoint coverage rows: 418 (committed ledger matches: true)
// </auto-generated>

using Opc.Ua.XRegistry;

namespace Opc.Ua.XRegistry
{
    public static partial class RegistrySharedNativeCatalog
    {
        private static void AddGeneratedTypes(RegistryNativeCatalog.Builder builder)
        {
            builder.AddType(Native("RegistryMetadataLabelsEntryDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryMetadataLabelsEntryDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryMetadataLabelsEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "String", "", false, false, null)
            ));
            builder.AddType(Native("RegistryMetadataLabelsDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryMetadataLabelsDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryMetadataLabelsDataType()
                , Field("Entries", "RegistryMetadataLabelsEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("RegistryMetadataDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryMetadataDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.XRegistry.RegistryMetadataDataType()
                , Field("Name", "String", "name", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Documentation", "String", "documentation", false, false, null)
                , Field("Self", "String", "self", false, false, null)
                , Field("Xid", "String", "xid", false, false, null)
                , Field("CreatedAt", "String", "createdat", false, false, null)
                , Field("ModifiedAt", "String", "modifiedat", false, false, null)
                , Field("Deprecated", "String", "deprecated", false, false, null)
                , Field("Epoch", "RegistryNumberValueDataType", "epoch", false, true, new RegistrySourceShape("uinteger"))
                , Field("Labels", "RegistryMetadataLabelsDataType", "labels", false, true, null)
                , Field("RegistryId", "String", "registryid", false, false, null)
                , Field("SpecVersion", "String", "specversion", false, false, null)
            ));
            builder.AddType(Native("RegistryCapabilitiesDocumentAvailableDataTypeValue", global::Opc.Ua.XRegistry.DataTypeIds.RegistryCapabilitiesDocumentAvailableDataTypeValue, "RegistryRecordDataType", false, static () => new global::Opc.Ua.XRegistry.RegistryCapabilitiesDocumentAvailableDataTypeValue()
                , Field("Mutable", "Boolean", "mutable", false, false, null)
            ));
            builder.AddType(Native("RegistryCapabilitiesDocumentAvailableEntryDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryCapabilitiesDocumentAvailableEntryDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryCapabilitiesDocumentAvailableEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "RegistryCapabilitiesDocumentAvailableDataTypeValue", "", false, true, null)
            ));
            builder.AddType(Native("RegistryCapabilitiesDocumentAvailableDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryCapabilitiesDocumentAvailableDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryCapabilitiesDocumentAvailableDataType()
                , Field("Entries", "RegistryCapabilitiesDocumentAvailableEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("RegistryCapabilitiesDocumentCompatibilitiesEntryDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryCapabilitiesDocumentCompatibilitiesEntryDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryCapabilitiesDocumentCompatibilitiesEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "RegistryArrayValueDataType", "", false, true, new RegistrySourceShape("array") { Item = new RegistrySourceShape("string") })
            ));
            builder.AddType(Native("RegistryCapabilitiesDocumentCompatibilitiesDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryCapabilitiesDocumentCompatibilitiesDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryCapabilitiesDocumentCompatibilitiesDataType()
                , Field("Entries", "RegistryCapabilitiesDocumentCompatibilitiesEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("RegistryCapabilitiesDocumentDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryCapabilitiesDocumentDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.XRegistry.RegistryCapabilitiesDocumentDataType()
                , Field("Available", "RegistryCapabilitiesDocumentAvailableDataType", "available", false, true, null)
                , Field("Compatibilities", "RegistryCapabilitiesDocumentCompatibilitiesDataType", "compatibilities", false, true, null)
                , Field("Flags", "String", "flags", true, false, null)
                , Field("Formats", "String", "formats", true, false, null)
                , Field("Ignores", "String", "ignores", true, false, null)
                , Field("Mutable", "String", "mutable", true, false, null)
                , Field("SpecVersions", "String", "specversions", true, false, null)
                , Field("VersionModes", "String", "versionmodes", true, false, null)
                , Field("Pagination", "Boolean", "pagination", false, false, null)
                , Field("ShortSelf", "Boolean", "shortself", false, false, null)
            ));
            builder.AddType(Native("RegistryAttributeMapEntryDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryAttributeMapEntryDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryAttributeMapEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "RegistryAttributeDefinitionDataType", "", false, true, null)
            ));
            builder.AddType(Native("RegistryAttributeMapDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryAttributeMapDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryAttributeMapDataType()
                , Field("Entries", "RegistryAttributeMapEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("RegistryConditionMapEntryDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryConditionMapEntryDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryConditionMapEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "RegistryConditionDataType", "", false, true, null)
            ));
            builder.AddType(Native("RegistryConditionMapDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryConditionMapDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryConditionMapDataType()
                , Field("Entries", "RegistryConditionMapEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("RegistryGroupModelMapEntryDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryGroupModelMapEntryDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryGroupModelMapEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "RegistryGroupModelDataType", "", false, true, null)
            ));
            builder.AddType(Native("RegistryGroupModelMapDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryGroupModelMapDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryGroupModelMapDataType()
                , Field("Entries", "RegistryGroupModelMapEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("RegistryResourceModelMapEntryDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryResourceModelMapEntryDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryResourceModelMapEntryDataType()
                , Field("Name", "String", "", false, false, null)
                , Field("Value", "RegistryResourceModelDataType", "", false, true, null)
            ));
            builder.AddType(Native("RegistryResourceModelMapDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryResourceModelMapDataType, "Structure", false, static () => new global::Opc.Ua.XRegistry.RegistryResourceModelMapDataType()
                , Field("Entries", "RegistryResourceModelMapEntryDataType", "", true, false, null)
            ));
            builder.AddType(Native("RegistryAttributeDefinitionDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryAttributeDefinitionDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.XRegistry.RegistryAttributeDefinitionDataType()
                , Field("Name", "String", "name", false, false, null)
                , Field("Type", "String", "type", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Required", "Boolean", "required", false, false, null)
                , Field("Default", "RegistryValueDataType", "default", false, true, null)
                , Field("Enum", "RegistryValueDataType", "enum", true, true, null)
                , Field("Attributes", "RegistryAttributeMapDataType", "attributes", false, true, null)
                , Field("Item", "RegistryAttributeDefinitionDataType", "item", false, true, null)
                , Field("IfValues", "RegistryConditionMapDataType", "ifvalues", false, true, null)
                , Field("Target", "String", "target", false, false, null)
                , Field("NameCharset", "String", "namecharset", false, false, null)
                , Field("Minimum", "RegistryValueDataType", "minimum", false, true, null)
                , Field("Maximum", "RegistryValueDataType", "maximum", false, true, null)
                , Field("Include", "String", "$include", false, false, null)
                , Field("Includes", "String", "$includes", true, false, null)
            ));
            builder.AddType(Native("RegistryConditionDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryConditionDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.XRegistry.RegistryConditionDataType()
                , Field("SiblingAttributes", "RegistryAttributeMapDataType", "siblingattributes", false, true, null)
            ));
            builder.AddType(Native("RegistryResourceModelDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryResourceModelDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.XRegistry.RegistryResourceModelDataType()
                , Field("Singular", "String", "singular", false, false, null)
                , Field("Plural", "String", "plural", false, false, null)
                , Field("ModelVersion", "String", "modelversion", false, false, null)
                , Field("ModelCompatibleWith", "String", "modelcompatiblewith", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Include", "String", "$include", false, false, null)
                , Field("Includes", "String", "$includes", true, false, null)
                , Field("Attributes", "RegistryAttributeMapDataType", "attributes", false, true, null)
                , Field("HasDocument", "Boolean", "hasdocument", false, false, null)
                , Field("MaxVersions", "RegistryValueDataType", "maxversions", false, true, null)
            ));
            builder.AddType(Native("RegistryGroupModelDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryGroupModelDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.XRegistry.RegistryGroupModelDataType()
                , Field("Singular", "String", "singular", false, false, null)
                , Field("Plural", "String", "plural", false, false, null)
                , Field("ModelVersion", "String", "modelversion", false, false, null)
                , Field("ModelCompatibleWith", "String", "modelcompatiblewith", false, false, null)
                , Field("Description", "String", "description", false, false, null)
                , Field("Include", "String", "$include", false, false, null)
                , Field("Includes", "String", "$includes", true, false, null)
                , Field("Attributes", "RegistryAttributeMapDataType", "attributes", false, true, null)
                , Field("Resources", "RegistryResourceModelMapDataType", "resources", false, true, null)
                , Field("ImportResources", "String", "ximportresources", true, false, null)
            ));
            builder.AddType(Native("RegistryModelDocumentDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryModelDocumentDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.XRegistry.RegistryModelDocumentDataType()
                , Field("Schema", "String", "$schema", false, false, null)
                , Field("ModelVersion", "String", "modelversion", false, false, null)
                , Field("Include", "String", "$include", false, false, null)
                , Field("Includes", "String", "$includes", true, false, null)
                , Field("Attributes", "RegistryAttributeMapDataType", "attributes", false, true, null)
                , Field("Groups", "RegistryGroupModelMapDataType", "groups", false, true, null)
            ));
            builder.AddType(Native("RegistryExtensionDefinitionDataType", global::Opc.Ua.XRegistry.DataTypeIds.RegistryExtensionDefinitionDataType, "RegistryRecordDataType", false, static () => new global::Opc.Ua.XRegistry.RegistryExtensionDefinitionDataType()
                , Field("Identity", "String", "identity", false, false, null)
                , Field("Version", "String", "version", false, false, null)
                , Field("Selectors", "String", "selectors", true, false, null)
                , Field("OptionModel", "RegistryAttributeDefinitionDataType", "optionModel", false, true, null)
                , Field("SemanticRules", "String", "semanticRules", true, false, null)
                , Field("Defaults", "RegistryObjectValueDataType", "defaults", false, true, null)
                , Field("NativeDependencies", "String", "nativeDependencies", true, false, null)
                , Field("Claims", "String", "claims", true, false, null)
            ));
            builder.AddMap(new RegistryNativeMapDescriptor("RegistryAttributeMapDataType", "RegistryAttributeMapEntryDataType", "RegistryAttributeDefinitionDataType") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("RegistryCapabilitiesDocumentAvailableDataType", "RegistryCapabilitiesDocumentAvailableEntryDataType", "RegistryCapabilitiesDocumentAvailableDataTypeValue") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("RegistryCapabilitiesDocumentCompatibilitiesDataType", "RegistryCapabilitiesDocumentCompatibilitiesEntryDataType", "RegistryArrayValueDataType") { ValueShape = new RegistrySourceShape("array") { Item = new RegistrySourceShape("string") } });
            builder.AddMap(new RegistryNativeMapDescriptor("RegistryConditionMapDataType", "RegistryConditionMapEntryDataType", "RegistryConditionDataType") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("RegistryGroupModelMapDataType", "RegistryGroupModelMapEntryDataType", "RegistryGroupModelDataType") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("RegistryMetadataLabelsDataType", "RegistryMetadataLabelsEntryDataType", "String") { ValueShape = null });
            builder.AddMap(new RegistryNativeMapDescriptor("RegistryResourceModelMapDataType", "RegistryResourceModelMapEntryDataType", "RegistryResourceModelDataType") { ValueShape = null });
        }
    }
}
